In [1]:
# Import Libraries and Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Read in US Census Bureau 2021 Household Pulse Survey data and analyze to determine fields that we will be using for our project

In [2]:
# Read the US Census Bureau 2021 Household Pulse Survey CSV files into DataFrames.
pulse2021_1q_file = 'Resources/pulse2021_puf_24.csv'
pulse2021_1q_df = pd.read_csv(pulse2021_1q_file)
pulse2021_2q_file = 'Resources/pulse2021_puf_29.csv'
pulse2021_2q_df = pd.read_csv(pulse2021_2q_file)
pulse2021_3q_file = 'Resources/pulse2021_puf_38.csv'
pulse2021_3q_df = pd.read_csv(pulse2021_3q_file)
pulse2021_4q_file = 'Resources/pulse2021_puf_39.csv'
pulse2021_4q_df = pd.read_csv(pulse2021_4q_file)
print("Input files have been read in")

Input files have been read in

In [3]:
# Set display options to show all rows and columns
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [4]:
#Display first 5 rows of 2021 dataframes
display(pulse2021_1q_df.head())
display(pulse2021_2q_df.head())
display(pulse2021_3q_df.head())
display(pulse2021_4q_df.head())

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,HWEIGHT,PWEIGHT,TBIRTH_YEAR,ABIRTH_YEAR,EGENDER,AGENDER,RHISPANIC,AHISPANIC,RRACE,ARACE,EEDUC,AEDUC,MS,THHLD_NUMPER,AHHLD_NUMPER,THHLD_NUMKID,AHHLD_NUMKID,THHLD_NUMADLT,RECVDVACC,DOSES,GETVACC,WHYNOT1,WHYNOT2,WHYNOT3,WHYNOT4,WHYNOT5,WHYNOT6,WHYNOT7,WHYNOT8,WHYNOT9,WHYNOT10,WHYNOT11,WHYNOTB1,WHYNOTB2,WHYNOTB3,WHYNOTB4,WHYNOTB5,WHYNOTB6,HADCOVID,WRKLOSS,EXPCTLOSS,ANYWORK,KINDWORK,RSNNOWRK,TW_START,UI_APPLY,UI_RECV,SSA_RECV,SSA_APPLY,SSAPGM1,SSAPGM2,SSAPGM3,SSAPGM4,SSAPGM5,SSALIKELY,SSAEXPCT1,SSAEXPCT2,SSAEXPCT3,SSAEXPCT4,SSAEXPCT5,SSADECISN,EIP,EIPSPND1,EIPSPND2,EIPSPND3,EIPSPND4,EIPSPND5,EIPSPND6,EIPSPND7,EIPSPND8,EIPSPND9,EIPSPND10,EIPSPND11,EIPSPND12,EIPSPND13,EXPNS_DIF,CHNGHOW1,CHNGHOW2,CHNGHOW3,CHNGHOW4,CHNGHOW5,CHNGHOW6,CHNGHOW7,CHNGHOW8,CHNGHOW9,CHNGHOW10,CHNGHOW11,CHNGHOW12,WHYCHNGD1,WHYCHNGD2,WHYCHNGD3,WHYCHNGD4,WHYCHNGD5,WHYCHNGD6,WHYCHNGD7,WHYCHNGD8,WHYCHNGD9,WHYCHNGD10,WHYCHNGD11,WHYCHNGD12,WHYCHNGD13,SPNDSRC1,SPNDSRC2,SPNDSRC3,SPNDSRC4,SPNDSRC5,SPNDSRC6,SPNDSRC7,SPNDSRC8,FEWRTRIPS,FEWRTRANS,PLNDTRIPS,CURFOODSUF,CHILDFOOD,FOODSUFRSN1,FOODSUFRSN2,FOODSUFRSN3,FOODSUFRSN4,FOODSUFRSN5,FREEFOOD,WHEREFREE1,WHEREFREE2,WHEREFREE3,WHEREFREE4,WHEREFREE5,WHEREFREE6,WHEREFREE7,SNAP_YN,TSPNDFOOD,TSPNDPRPD,ANXIOUS,WORRY,INTEREST,DOWN,HLTHINS1,HLTHINS2,HLTHINS3,HLTHINS4,HLTHINS5,HLTHINS6,HLTHINS7,HLTHINS8,PRIVHLTH,PUBHLTH,DELAY,NOTGET,PRESCRIPT,MH_SVCS,MH_NOTGET,TENURE,LIVQTR,RENTCUR,MORTCUR,MORTCONF,EVICT,FORCLOSE,ENROLL1,ENROLL2,ENROLL3,TEACH1,TEACH2,TEACH3,TEACH4,TEACH5,COMPAVAIL,COMP1,COMP2,COMP3,INTRNTAVAIL,INTRNT1,INTRNT2,INTRNT3,SCHLHRS,TSTDY_HRS,TCH_HRS,TNUM_PS,PSPLANS1,PSPLANS2,PSPLANS3,PSPLANS4,PSPLANS5,PSPLANS6,PSCHNG1,PSCHNG2,PSCHNG3,PSCHNG4,PSCHNG5,PSCHNG6,PSCHNG7,PSWHYCHG1,PSWHYCHG2,PSWHYCHG3,PSWHYCHG4,PSWHYCHG5,PSWHYCHG6,PSWHYCHG7,PSWHYCHG8,PSWHYCHG9,INCOME
0,V240000001S30011152510122,24,1,NaN,2,3263.656263,6298.128284,1957,2,2,2,1,2,1,2,3,2,1,2,2,0,2,2,2,-88,2,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-88,-88,-88,-88,-88,-88,2,2,2,2,-88,7,2,2,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,-99,-99,-99,-99,-99,-99,1,1,-99,-99,-99,-99,-99,2,1,-99,-99,-99,-99,1,-99,1,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,1,-99,-99,-99,-99,1,-99,-99,1,3,1,1,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,2,125,25,2,1,1,2,1,2,1,-99,-99,-99,-99,-99,1,1,1,2,1,2,2,2,2,-88,1,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3
1,V240000001S33011384810122,24,1,NaN,2,1751.171303,3379.369831,1977,2,1,2,1,2,1,2,6,2,3,2,2,0,2,2,2,-88,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,1,2,-88,1,2,-88,2,2,-88,-88,-88,-88,-88,4,-88,-88,-88,-88,-88,1,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,-99,-99,-99,2,2,1,1,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,2,750,500,1,1,1,1,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,-88,1,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,1,-99,-99,-99,1,-99,-99,1,-99,-99,-99,-99,-99,-99,-88,-88,-88,-88,-88,-88,-88,-88,-88,4
2,V240000001S34010333300122,24,1,NaN,2,1488.642062,1436.373490,1944,2,2,2,1,2,1,2,4,2,1,2,2,1,2,1,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,2,-88,7,-99,2,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,2,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,1,3,1,1,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,2,-99,5,1,1,1,1,-99,-99,1,-99,-99,-99,-99,-99,3,1,1,1,2,2,2,1,2,-88,-88,-88,-88,-88,-99,-99,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2
3,V240000001S37010409600112,24,1,NaN,2,655.744049,632.719841,1947,2,2,2,1,2,1,2,6,2,2,1,2,0,2,1,2,-88,2,1,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-88,-88,-88,-88,-88,-88,2,2,2,2,-88,4,-99,2,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,1,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,2,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-99,-99,-99,-99,-99,-99,-99,-99,1,3,1,2,-88,-99,-99,-99,-99,-99,2,-88,-88,-88,-88,-88,-88,-88,2,-99,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
4,V240000001S37010979700122,24,1,NaN,2,3569.279242,6887.912432,1978,2,1,2,1,2,4,2,4,2,1,4,2,2,2,2,2,-88,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,1,2,1,2,-88,1,2,-88,2,2,-88,-88,-88,-88,-88,4,-88,-88,-88,-88,-88,1,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,4,1,1,-99,1,-99,1,-99,-99,1,-99,-99,-99,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88.0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,HWEIGHT,PWEIGHT,TBIRTH_YEAR,ABIRTH_YEAR,EGENDER,AGENDER,RHISPANIC,AHISPANIC,RRACE,ARACE,EEDUC,AEDUC,MS,THHLD_NUMPER,AHHLD_NUMPER,THHLD_NUMKID,AHHLD_NUMKID,THHLD_NUMADLT,ACTVDUTY1,ACTVDUTY2,ACTVDUTY3,ACTVDUTY4,ACTVDUTY5,RECVDVACC,DOSES,GETVACRV,WHYNOT1,WHYNOT2,WHYNOT3,WHYNOT4,WHYNOT5,WHYNOT6,WHYNOT7,WHYNOT8,WHYNOT9,WHYNOT10,WHYNOT11,WHYNOTB1,WHYNOTB2,WHYNOTB3,WHYNOTB4,WHYNOTB5,WHYNOTB6,COVPRVNT,HADCOVID,WRKLOSSRV,EXPCTLOSS,ANYWORK,KINDWORK,RSNNOWRKRV,TW_YN,TW_COV,WKVOL,SETTING,UI_APPLYRV,UI_RECVRV,UI_RECVNOW,SSA_RECV,SSA_APPLYRV,SSAPGMRV1,SSAPGMRV2,SSAPGMRV3,SSAPGMRV4,SSAPGMRV5,SSALIKELYRV,SSAEXPCT1,SSAEXPCT2,SSAEXPCT3,SSAEXPCT4,SSAEXPCT5,SSADECISN,EIP_YN,EIPRV,EIPSPND1,EIPSPND2,EIPSPND3,EIPSPND4,EIPSPND5,EIPSPND6,EIPSPND7,EIPSPND8,EIPSPND9,EIPSPND10,EIPSPND11,EIPSPND12,EIPSPND13,EXPNS_DIF,CHNGSHOP1,CHNGSHOP2,CHNGSHOP3,CHNGSVCS1,CHNGSVCS2,CHNGSVCS3,CHNGSHP1ML,CHNGSHP2ML,CHNGSHP3ML,CHNGSVC1ML,CHNGSVC2ML,CHNGSVC3ML,CASHUSE,WHYCHNGD1,WHYCHNGD2,WHYCHNGD3,WHYCHNGD4,WHYCHNGD5,WHYCHNGD6,WHYCHNGD7,WHYCHNGD8,WHYCHNGD9,WHYCHNGD10,WHYCHNGD11,WHYCHNGD12,WHYCHNGD13,SPNDSRC1,SPNDSRC2,SPNDSRC3,SPNDSRC4,SPNDSRC5,SPNDSRC6,SPNDSRC7,SPNDSRC8,SPNDSRC9,FEWRTRIP1,FEWRTRIP2,FEWRTRIP3,PRVRIDESHR,FEWRTRANS,PLNDTRIPS,CURFOODSUF,CHILDFOOD,FOODRSNRV1,FOODRSNRV2,FOODRSNRV3,FOODRSNRV4,FREEFOOD,SNAP_YN,TSPNDFOOD,TSPNDPRPD,ANXIOUS,WORRY,INTEREST,DOWN,HLTHINS1,HLTHINS2,HLTHINS3,HLTHINS4,HLTHINS5,HLTHINS6,HLTHINS7,HLTHINS8,PRIVHLTH,PUBHLTH,DELAY,NOTGET,TELEHLTH,TELECHLD,PRESCRIPT,MH_SVCS,MH_NOTGET,PRVNTIVE,PRVNTWHY1,PRVNTWHY2,PRVNTWHY3,PRVNTWHY4,PRVNTWHY5,PRVNTWHY6,PRVNTWHY7,SEEING,HEARING,REMEMBERING,MOBILITY,TENURE,LIVQTRRV,RENTCUR,MORTCUR,MORTCONF,EVICT,FORCLOSE,ENRPUBCHK,ENRPRVCHK,ENRHMSCHK,TENROLLPUB,TENROLLPRV,TENROLLHMSCH,ENROLLNONE,TEACH1,TEACH2,TEACH3,TEACH4,TEACH5,TEACH6,TEACH7,TEACH8,HYBRID,COMPAVAIL,INTRNTAVAIL,INTRNTRV1,INTRNTRV2,INTRNTRV3,INTRNTRV4,SCHLHRS,SCHLFOOD,SCHLFDHLP1,SCHLFDHLP2,SCHLFDHLP3,SCHLFDHLP4,CHLDCARE,CHLDIMPCT1,CHLDIMPCT2,CHLDIMPCT3,CHLDIMPCT4,CHLDIMPCT5,CHLDIMPCT6,CHLDIMPCT7,CHLDIMPCT8,CHLDIMPCT9,TNUM_PS,PSCHNG1,PSCHNG2,PSCHNG3,PSCHNG4,PSCHNG5,PSCHNG6,PSCHNG7,PSWHYCHG1,PSWHYCHG2,PSWHYCHG3,PSWHYCHG4,PSWHYCHG5,PSWHYCHG6,PSWHYCHG7,PSWHYCHG8,PSWHYCHG9,INCOME
0,V290000001S18010005900121,29,1,NaN,2,828.050575,1565.261005,1977,2,2,2,1,2,1,2,7,2,1,4,2,2,2,2,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,2,1,2,-88,1,1,1,15,2,2,-88,2,2,-88,-88,-88,-88,-88,4,-88,-88,-88,-88,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,4,1,1,1,1,1,1,2,2,2,2,2,2,2,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,2,-88,2,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
1,V290000001S30010947000111,29,1,NaN,2,778.499706,2207.392766,1952,2,1,2,1,2,1,2,7,2,1,4,2,1,2,3,1,-99,-99,-99,-99,2,-88,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,2,-88,7,2,-88,1,2,2,2,-88,1,1,1,-99,-99,-99,-99,-88,-88,-88,-88,-88,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,2,2,2,2,-88,-88,-88,-88,-88,-88,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,1,1,-99,-99,-99,-99,1,-99,-99,-99,1,2,-88,2,1,-88,-88,-88,-88,-88,2,1,200,250,1,1,1,1,2,1,1,1,1,1,2,2,1,1,2,2,2,2,2,2,2,2,-88,-88,-88,-88,-88,-88,-88,1,1,1,1,1,2,-88,-88,-88,-88,-88,1,-99,-99,1,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,2,1,1,-99,1,-99,-99,1,2,-88,-88,-88,-88,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,7
2,V290000001S30011651510121,29,1,NaN,2,3510.046226,6635.027677,2000,2,2,2,1,2,1,2,4,2,5,2,2,0,2,2,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,1,2,2,1,3,-88,2,-88,1,1,2,2,-88,2,2,-88,-88,-88,-88,-88,4,-88,-88,-88,-88,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,2,2,2,2,-88,-88,-88,-88,-88,-88,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,2,-88,2,1,-88,-88,-88,-88,-88,2,2,100,30,1,1,1,1,-88,-88,-88,-88,-88,-88,-88,-88,3,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
3,V290000001S31011267510121,29,1,NaN,2,845.921367,799.521050,1965,2,2,2,1,2,1,2,4,2,4,1,2,0,2,1,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,2,2,-88,6,2,-88,2,-88,2,2,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,1,2,1,2,2,2,2,-88,1,-88,-88,-88,2,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,1,-99,1,-99,-99,-99,1,2,-88,2,2,-88,-99,-99,-99,1,2,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
4,V290000001S34010044300121,29,1,NaN,2,7376.505002,6971.890353,1948,2,1,2,1,2,1,2,3,2,2,1,2,0,2,1,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,2,2,-88,7,2,-88,2,-88,2,2,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,2,2,2,2,-88,-88,-88,-88,-88,-88,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,1,2,-88,2,1,-88,-88,-88,-88,-88,2,2,150,40,1,1,1,1,-99,-99,-99,1,-99,-99,-99,-99,3,1,2,2,2,-88,2,2,2,-88,-88,-88,-88,-88,-88,-88,-88,2,1,1,2,3,4,1,-88,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,HWEIGHT,PWEIGHT,TBIRTH_YEAR,ABIRTH_YEAR,RHISPANIC,AHISPANIC,RRACE,ARACE,EEDUC,AEDUC,MS,EGENID_BIRTH,AGENID_BIRTH,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,AHHLD_NUMPER,THHLD_NUMKID,AHHLD_NUMKID,THHLD_NUMADLT,KIDS_LT5Y,KIDS_5_11Y,KIDS_12_17Y,ENRPUBCHK,ENRPRVCHK,ENRHMSCHK,TENROLLPUB,TENROLLPRV,TENROLLHMSCH,ENROLLNONE,ACTVDUTY1,ACTVDUTY2,ACTVDUTY3,ACTVDUTY4,ACTVDUTY5,RECVDVACC,DOSESRV,GETVACRV,WHYNORV1,WHYNORV2,WHYNORV3,WHYNORV4,WHYNORV5,WHYNORV6,WHYNORV7,WHYNORV8,WHYNORV9,WHYNORV10,WHYNORV11,WHYNORV12,WHYNORV13,KIDDOSES,KIDGETVAC,KIDWHYNO1,KIDWHYNO2,KIDWHYNO3,KIDWHYNO4,KIDWHYNO5,KIDWHYNO6,KIDWHYNO7,KIDWHYNO8,KIDWHYNO9,KIDWHYNO10,KIDWHYNO11,KIDWHYNO12,KIDWHYNO13,KIDWHYNO14,HADCOVID,WRKLOSSRV,ANYWORK,KINDWORK,RSNNOWRKRV,WKVOL,SETTING,CHLDCARE,CHLDIMPCT1,CHLDIMPCT2,CHLDIMPCT3,CHLDIMPCT4,CHLDIMPCT5,CHLDIMPCT6,CHLDIMPCT7,CHLDIMPCT8,CHLDIMPCT9,CTC_YN,CTC_USE,CTCSPND1,CTCSPND2,CTCSPND3,CTCSPND4,CTCSPND5,CTCSPND6,CTCSPND7,CTCSPND8,CTCSPND9,CTCSPND10,CTCSPND11,CTCSPND12,CTCSPND13,CTCSPND14,CTCSPND15,CTCSPND16,CTCSPND17,EXPNS_DIF,ACTIVITY1,ACTIVITY2,ACTIVITY3,ACTIVITY4,ACTIVITY5,ACTIVITY6,SPND_SRC1,SPND_SRC2,SPND_SRC3,SPND_SRC4,SPND_SRC5,SPND_SRC6,SPND_SRC7,SPND_SRC8,SPND_SRC9,SPND_SRC10,SPND_SRC11,SPND_SRC12,CURFOODSUF,CHILDFOOD,FOODRSNRV1,FOODRSNRV2,FOODRSNRV3,FOODRSNRV4,FREEFOOD,SCHLFDHLP1,SCHLFDHLP2,SCHLFDHLP3,SCHLFDHLP4,NOSCHLFDHLP,SNAP_YN,ANXIOUS,WORRY,INTEREST,DOWN,PRESCRIPT,MH_SVCS,MH_NOTGET,HLTHINS1,HLTHINS2,HLTHINS3,HLTHINS4,HLTHINS5,HLTHINS6,HLTHINS7,HLTHINS8,PRIVHLTH,PUBHLTH,TELEHLTH,TH_ADLT_PHON,TH_ADLT_VID,TELECHLD,TH_CHLD_PHON,TH_CHLD_VID,PRVNTIVE,SEEING,HEARING,REMEMBERING,MOBILITY,TENURE,LIVQTRRV,RENTCUR,MORTCUR,MORTCONF,TMNTHSBHND,RENTASSIST,EVICT,FORCLOSE,ENERGY,HSE_TEMP,ENRGY_BILL,SUMMER_ED1,SUMMER_ED2,SUMMER_ED3,SUMMER_ED4,TNUM_PS,PSCHNG1,PSCHNG2,PSCHNG3,PSCHNG4,PSCHNG5,PSCHNG6,PSCHNG7,PSWHYCHG1,PSWHYCHG2,PSWHYCHG3,PSWHYCHG4,PSWHYCHG5,PSWHYCHG6,PSWHYCHG7,PSWHYCHG8,PSWHYCHG9,INCOME
0,V380000001,38,28,NaN,2,662.915385,636.350100,1965,2,1,2,1,2,6,2,5,1,2,1,2,1,2,0,2,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,1,2,-88,1,18,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,1,1,1,2,2,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,2,1,2,2,2,2,1,1,2,2,2,2,2,2,2,1,2,2,-88,-88,-88,-88,-88,-88,2,1,2,1,2,2,-88,1,4,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,6
1,V380000002,38,35,NaN,4,536.164089,1046.123591,1952,2,1,2,1,2,4,2,1,2,2,2,2,2,2,0,2,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,1,4,-88,1,19,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,1,1,1,2,1,2,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,1,1,1,1,2,2,2,2,1,1,-99,-99,-99,-99,-99,1,1,2,-88,-88,-88,-88,-88,-88,2,1,1,1,1,2,-88,-88,-88,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,5
2,V380000003,38,2,NaN,4,399.481562,385.689765,1954,2,1,2,1,2,3,2,2,2,2,2,2,1,2,0,2,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,-88,7,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,1,1,1,-99,1,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,1,1,1,1,2,2,2,1,-99,1,-99,-99,-99,-99,-99,1,1,2,-88,-88,-88,-88,-88,-88,1,1,2,1,1,2,-88,-88,-88,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,4
3,V380000004,38,55,NaN,3,6385.449077,11877.653310,1945,2,1,2,1,2,3,2,1,2,2,2,2,2,2,0,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,-88,7,1,19,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,1,1,1,2,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,1,1,1,1,2,2,2,1,2,1,2,2,2,2,-99,1,1,1,-99,1,-88,-88,-88,-88,1,1,1,1,1,2,-88,-88,-88,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
4,V380000005,38,42,NaN,1,21493.336617,59467.996796,1961,2,1,2,1,1,3,2,1,1,2,1,5,4,1,1,2,3,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,1,-99,-99,-99,-99,2,-88,3,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-88,-88,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,-88,9,1,19,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,1,2,2,2,2,2,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-99,-99,-99,-99,-99,2,1,1,1,1,2,2,2,1,2,2,2,2,2,2,2,1,2,2,-88,-88,2,-88,-88,3,4,4,4,4,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,HWEIGHT,PWEIGHT,TBIRTH_YEAR,ABIRTH_YEAR,RHISPANIC,AHISPANIC,RRACE,ARACE,EEDUC,AEDUC,MS,EGENID_BIRTH,AGENID_BIRTH,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,AHHLD_NUMPER,THHLD_NUMKID,AHHLD_NUMKID,THHLD_NUMADLT,KIDS_LT5Y,KIDS_5_11Y,KIDS_12_17Y,ENRPUBCHK,ENRPRVCHK,ENRHMSCHK,TENROLLPUB,TENROLLPRV,TENROLLHMSCH,ENROLLNONE,ACTVDUTY1,ACTVDUTY2,ACTVDUTY3,ACTVDUTY4,ACTVDUTY5,RECVDVACC,DOSESRV,GETVACRV,WHYNORV1,WHYNORV2,WHYNORV3,WHYNORV4,WHYNORV5,WHYNORV6,WHYNORV7,WHYNORV8,WHYNORV9,WHYNORV10,WHYNORV11,WHYNORV12,WHYNORV13,KIDDOSES,KIDGETVAC,KIDWHYNO1,KIDWHYNO2,KIDWHYNO3,KIDWHYNO4,KIDWHYNO5,KIDWHYNO6,KIDWHYNO7,KIDWHYNO8,KIDWHYNO9,KIDWHYNO10,KIDWHYNO11,KIDWHYNO12,KIDWHYNO13,KIDWHYNO14,HADCOVID,WRKLOSSRV,ANYWORK,KINDWORK,RSNNOWRKRV,WKVOL,SETTING,CHLDCARE,CHLDIMPCT1,CHLDIMPCT2,CHLDIMPCT3,CHLDIMPCT4,CHLDIMPCT5,CHLDIMPCT6,CHLDIMPCT7,CHLDIMPCT8,CHLDIMPCT9,CTC_YN,CTC_USE,CTCSPND1,CTCSPND2,CTCSPND3,CTCSPND4,CTCSPND5,CTCSPND6,CTCSPND7,CTCSPND8,CTCSPND9,CTCSPND10,CTCSPND11,CTCSPND12,CTCSPND13,CTCSPND14,CTCSPND15,CTCSPND16,CTCSPND17,EXPNS_DIF,ACTIVITY1,ACTIVITY2,ACTIVITY3,ACTIVITY4,ACTIVITY5,ACTIVITY6,SPND_SRC1,SPND_SRC2,SPND_SRC3,SPND_SRC4,SPND_SRC5,SPND_SRC6,SPND_SRC7,SPND_SRC8,SPND_SRC9,SPND_SRC10,SPND_SRC11,SPND_SRC12,CURFOODSUF,CHILDFOOD,FOODRSNRV1,FOODRSNRV2,FOODRSNRV3,FOODRSNRV4,FREEFOOD,SCHLFDHLP1,SCHLFDHLP2,SCHLFDHLP3,SCHLFDHLP4,NOSCHLFDHLP,SNAP_YN,ANXIOUS,WORRY,INTEREST,DOWN,PRESCRIPT,MH_SVCS,MH_NOTGET,HLTHINS1,HLTHINS2,HLTHINS3,HLTHINS4,HLTHINS5,HLTHINS6,HLTHINS7,HLTHINS8,PRIVHLTH,PUBHLTH,TELEHLTH,TH_ADLT_PHON,TH_ADLT_VID,TELECHLD,TH_CHLD_PHON,TH_CHLD_VID,PRVNTIVE,SEEING,HEARING,REMEMBERING,MOBILITY,TENURE,LIVQTRRV,RENTCUR,MORTCUR,MORTCONF,TMNTHSBHND,RENTASSIST,EVICT,FORCLOSE,ENERGY,HSE_TEMP,ENRGY_BILL,SUMMER_ED1,SUMMER_ED2,SUMMER_ED3,SUMMER_ED4,TNUM_PS,PSCHNG1,PSCHNG2,PSCHNG3,PSCHNG4,PSCHNG5,PSCHNG6,PSCHNG7,PSWHYCHG1,PSWHYCHG2,PSWHYCHG3,PSWHYCHG4,PSWHYCHG5,PSWHYCHG6,PSWHYCHG7,PSWHYCHG8,PSWHYCHG9,INCOME
0,V390000001S30010132000112,39,1,NaN,2,1560.107273,2950.831036,1955,2,1,2,1,2,4,2,1,1,2,1,2,2,2,0,2,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,-88,7,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,1,1,1,-99,1,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,1,1,2,-99,1,2,2,-99,-99,1,-99,1,-99,-99,-99,1,1,2,-88,-88,-88,-88,-88,-88,2,2,2,2,2,2,-88,1,4,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,5
1,V390000001S30010930100112,39,1,NaN,2,2015.111681,1905.719622,1955,2,1,2,1,2,4,2,1,2,2,2,-99,4,2,3,2,1,-99,1,-99,1,-99,-99,1,-99,-99,-99,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,1,-99,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88
2,V390000001S96010845500122,39,1,NaN,2,2916.377523,8274.178438,1999,2,1,2,4,2,4,2,5,2,2,2,3,3,2,0,2,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,-88,1,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,1,1,1,1,1,2,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,2,2,3,2,2,2,2,1,2,2,2,2,2,2,2,1,2,2,-88,-88,-88,-88,-88,-88,1,1,2,1,2,2,-88,1,4,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,1,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,1,-99,-99,3
3,V390000001S98010895010122,39,1,NaN,2,989.102446,2806.224527,1935,2,1,2,1,2,7,2,1,1,2,1,2,3,2,0,2,3,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,2,-88,7,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,2,2,1,1,2,1,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,1,1,1,1,2,2,2,-99,-99,1,2,2,2,2,1,3,1,1,1,-99,-88,-88,-88,-88,1,1,1,2,1,2,-88,-88,-88,-88,-88,-88,-88,4,4,4,-88,-88,-88,-88,0,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,7
4,V390000001S98010931110112,39,1,NaN,2,786.707174,1488.000207,1969,2,1,2,2,2,4,2,3,2,2,2,2,2,2,0,2,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,1,-99,-99,-99,-99,1,1,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,2,1,2,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,-88,3,1,1,1,2,2,2,1,1,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-88,-88,-88,-88,-88,2,-88,-88,-88,-88,-88,2,3,3,1,1,2,2,2,1,2,2,2,2,2,2,2,1,2,2,-88,-88,-88,-88,-88,-88,2,1,2,1,3,6,2,-88,1,1,4,3,-88,4,4,3,-88,-88,-88,-88,1,1,-99,-99,-99,-99,-99,-99,-88,-88,-88,-88,-88,-88,-88,-88,-88,4

In [5]:
#Get shape of data files
display(pulse2021_1q_df.shape)
display(pulse2021_2q_df.shape)
display(pulse2021_3q_df.shape)
display(pulse2021_4q_df.shape)

(77122, 204)

(78467, 239)

(59833, 202)

(57064, 202)

In [6]:
#Get information about data fields
display(pulse2021_1q_df.info())
display(pulse2021_2q_df.info())
display(pulse2021_3q_df.info())
display(pulse2021_4q_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77122 entries, 0 to 77121
Columns: 204 entries, SCRAM to INCOME
dtypes: float64(4), int64(199), object(1)
memory usage: 120.0+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78467 entries, 0 to 78466
Columns: 239 entries, SCRAM to INCOME
dtypes: float64(3), int64(235), object(1)
memory usage: 143.1+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59833 entries, 0 to 59832
Columns: 202 entries, SCRAM to INCOME
dtypes: float64(3), int64(198), object(1)
memory usage: 92.2+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57064 entries, 0 to 57063
Columns: 202 entries, SCRAM to INCOME
dtypes: float64(3), int64(198), object(1)
memory usage: 87.9+ MB

None

In [7]:
# Describe non-numeric fields
display(pulse2021_1q_df.describe(include='O'))
display(pulse2021_2q_df.describe(include='O'))
display(pulse2021_3q_df.describe(include='O'))
display(pulse2021_4q_df.describe(include='O'))

                            SCRAM
count                       77122
unique                      77122
top     V240000001S30011152510122
freq                            1

                            SCRAM
count                       78467
unique                      78467
top     V290000001S18010005900121
freq                            1

             SCRAM
count        59833
unique       59833
top     V380000001
freq             1

                            SCRAM
count                       57064
unique                      57064
top     V390000001S30010132000112
freq                            1

In [8]:
# Get list of columns
pulse2021_1q_df_cols_list = pulse2021_1q_df.columns
display(pulse2021_1q_df_cols_list)
pulse2021_2q_df_cols_list = pulse2021_2q_df.columns
display(pulse2021_2q_df_cols_list)
pulse2021_3q_df_cols_list = pulse2021_3q_df.columns
display(pulse2021_3q_df_cols_list)
pulse2021_4q_df_cols_list = pulse2021_4q_df.columns
display(pulse2021_4q_df_cols_list)

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'HWEIGHT', 'PWEIGHT',
       'TBIRTH_YEAR', 'ABIRTH_YEAR', 'EGENDER',
       ...
       'PSWHYCHG1', 'PSWHYCHG2', 'PSWHYCHG3', 'PSWHYCHG4', 'PSWHYCHG5',
       'PSWHYCHG6', 'PSWHYCHG7', 'PSWHYCHG8', 'PSWHYCHG9', 'INCOME'],
      dtype='object', length=204)

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'HWEIGHT', 'PWEIGHT',
       'TBIRTH_YEAR', 'ABIRTH_YEAR', 'EGENDER',
       ...
       'PSWHYCHG1', 'PSWHYCHG2', 'PSWHYCHG3', 'PSWHYCHG4', 'PSWHYCHG5',
       'PSWHYCHG6', 'PSWHYCHG7', 'PSWHYCHG8', 'PSWHYCHG9', 'INCOME'],
      dtype='object', length=239)

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'HWEIGHT', 'PWEIGHT',
       'TBIRTH_YEAR', 'ABIRTH_YEAR', 'RHISPANIC',
       ...
       'PSWHYCHG1', 'PSWHYCHG2', 'PSWHYCHG3', 'PSWHYCHG4', 'PSWHYCHG5',
       'PSWHYCHG6', 'PSWHYCHG7', 'PSWHYCHG8', 'PSWHYCHG9', 'INCOME'],
      dtype='object', length=202)

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'HWEIGHT', 'PWEIGHT',
       'TBIRTH_YEAR', 'ABIRTH_YEAR', 'RHISPANIC',
       ...
       'PSWHYCHG1', 'PSWHYCHG2', 'PSWHYCHG3', 'PSWHYCHG4', 'PSWHYCHG5',
       'PSWHYCHG6', 'PSWHYCHG7', 'PSWHYCHG8', 'PSWHYCHG9', 'INCOME'],
      dtype='object', length=202)

In [9]:
# Survey columns that may be included in our analysis
analysis_survey_cols = ['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION','TBIRTH_YEAR', 'RHISPANIC', 'RRACE',
                         'EEDUC', 'MS', 'GENID_DESCRIBE', 'SEXUAL_ORIENTATION', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID',
                         'LONGCOVID', 'SYMPTMIMPCT','ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY',
                         'REMEMBERING', 'SELFCARE', 'UNDERSTAND', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'PRICECHNG',
                         'PRICESTRESS', 'PRICECONCRN', 'EXPNS_DIF', 'TWDAYS', 'CURFOODSUF', 'FREEFOOD', 'TSPNDFOOD',
                         'TSPNDPRPD', 'ND_DISPLACE', 'TENURE', 'PRIVHLTH', 'PUBHLTH','MEDICAID', 'INCOME', 'HWEIGHT',
                         'PWEIGHT', 'WHENCOVID', 'ACTIVITY2']

# Note:  WHENCOVID response is only one column, it was split into three responses WHENCOVIDRV1,
#        WHENCOVIDRV2, and WHENCOVIDRV3 in later surveys
#        We captured 'ACTIVITY2' (Teleworked or Worked from Home).  We may be able to use this
#        column field in conjunction with 'TWDAYS' column in our analysis.  We will assess this
#        and determine if we want to include in our analysis.

In [10]:
# Identify survey columns that may be used for analysis

survey_cols_2021_3_4q = ['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION','TBIRTH_YEAR', 'RHISPANIC', 'RRACE',
                       'EEDUC', 'MS', 'GENID_DESCRIBE', 'SEXUAL_ORIENTATION', 'THHLD_NUMPER', 'RECVDVACC',
                       'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY',
                       'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF',
                       'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME', 'HWEIGHT', 'PWEIGHT', 'ACTIVITY2']
# Survey columns that are not in the 3q and 4q files:
#     'TWDAYS' - We captured 'ACTIVITY2' (Teleworked or Worked from Home).
#                We may be able to use this column field in conjunction with 'TWDAYS' column in our analysis.
#                We will assess this and determine if we want to include in our analysis.
##    'LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
##    'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID'

survey_cols_2021_2q = ['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION','TBIRTH_YEAR', 'RHISPANIC', 'RRACE',
                       'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST',
                       'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV', 'ANYWORK',
                       'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH',
                       'INCOME', 'HWEIGHT', 'PWEIGHT', 'EGENDER', 'TW_YN']
# Survey columns that are not in the 2q file:
#     'TWDAYS' & 'ACTIVITY2' - We captured 'TW_YN' (Teleworking start due to COVID).
#                We may be able to use this column field in conjunction with 'TWDAYS' &  'ACTIVITY2'
#                columns in our analysis.  We will assess this and determine if we want to include in our analysis.
#     'GENID_DESCRIBE' - We captured 'EGENDER' and will use this for gender in our analysis 
##    'LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
##    'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID'
##    'GENID_DESCRIBE', 'SEXUAL_ORIENTATION', 'ACTIVITY2'

survey_cols_2021_1q = ['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION','TBIRTH_YEAR', 'RHISPANIC', 'RRACE',
                       'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST',
                       'DOWN', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH',
                       'PUBHLTH', 'INCOME', 'HWEIGHT', 'PWEIGHT', 'EGENDER']
# Survey columns that are not in the 1q file:
#     'GENID_DESCRIBE' - We captured 'EGENDER' and will use this for gender in our analysis 
##    'LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
##    'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID'
##    'GENID_DESCRIBE', 'SEXUAL_ORIENTATION', 'ACTIVITY2'
##    'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV', 'TW_YN'

In [11]:
# Create smaller dataframes to use for analysis
pulse2021_1q_analysis_df = pulse2021_1q_df[survey_cols_2021_1q]
pulse2021_2q_analysis_df = pulse2021_2q_df[survey_cols_2021_2q]
pulse2021_3q_analysis_df = pulse2021_3q_df[survey_cols_2021_3_4q]
pulse2021_4q_analysis_df = pulse2021_4q_df[survey_cols_2021_3_4q]

In [12]:
# Display first 5 rows of analysis dataframes
display(pulse2021_1q_analysis_df.head())
display(pulse2021_2q_analysis_df.head())
display(pulse2021_3q_analysis_df.head())
display(pulse2021_4q_analysis_df.head())

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER
0,V240000001S30011152510122,24,1,NaN,2,1957,1,1,3,1,2,2,2,2,1,1,2,2,-88,2,1,2,2,1,1,3,3263.656263,6298.128284,2
1,V240000001S33011384810122,24,1,NaN,2,1977,1,1,6,3,2,2,2,1,1,1,1,1,2,1,1,2,2,1,2,4,1751.171303,3379.369831,1
2,V240000001S34010333300122,24,1,NaN,2,1944,1,1,4,1,2,1,2,1,1,1,1,2,-88,2,1,2,1,3,1,2,1488.642062,1436.373490,2
3,V240000001S37010409600112,24,1,NaN,2,1947,1,1,6,2,1,2,2,-88,-88,-88,-88,2,-88,2,2,2,-88,3,3,-88,655.744049,632.719841,2
4,V240000001S37010979700122,24,1,NaN,2,1978,1,4,4,1,4,2,2,-88,-88,-88,-88,1,2,4,-88,-88,-88,3,3,-88,3569.279242,6887.912432,1

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,TW_YN
0,V290000001S18010005900121,29,1,NaN,2,1977,1,1,7,1,4,1,2,-88,-88,-88,-88,-88,-88,-88,-88,2,1,2,4,2,-88,-88,3,3,-88,828.050575,1565.261005,2,1
1,V290000001S30010947000111,29,1,NaN,2,1952,1,1,7,1,4,2,2,1,1,1,1,1,1,1,1,2,2,-88,1,1,2,1,1,1,7,778.499706,2207.392766,1,2
2,V290000001S30011651510121,29,1,NaN,2,2000,1,1,4,5,2,1,1,1,1,1,1,-88,-88,-88,-88,2,1,3,1,1,2,-88,3,3,-88,3510.046226,6635.027677,2,2
3,V290000001S31011267510121,29,1,NaN,2,1965,1,1,4,4,1,1,2,-88,-88,-88,-88,-88,-88,-88,-88,2,2,-88,2,2,2,-88,3,3,-88,845.921367,799.521050,2,2
4,V290000001S34010044300121,29,1,NaN,2,1948,1,1,3,2,1,1,2,1,1,1,1,2,1,2,1,2,2,-88,1,1,2,3,3,1,3,7376.505002,6971.890353,1,2

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2
0,V380000001,38,28,NaN,2,1965,1,1,6,5,1,2,1,1,2,2,1,2,2,2,1,1,2,2,1,2,1,1,2,2,1,2,6,662.915385,636.350100,1
1,V380000002,38,35,NaN,4,1952,1,1,4,1,2,2,2,1,2,1,1,1,1,2,1,1,1,2,1,4,1,1,2,1,1,1,5,536.164089,1046.123591,1
2,V380000003,38,2,NaN,4,1954,1,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,2,2,2,-88,1,1,2,1,1,1,4,399.481562,385.689765,-99
3,V380000004,38,55,NaN,3,1945,1,1,3,1,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,-88,1,1,2,1,1,1,-88,6385.449077,11877.653310,2
4,V380000005,38,42,NaN,1,1961,1,1,3,1,1,5,4,2,2,1,1,1,1,4,4,4,4,2,2,-88,3,1,2,-88,1,2,-88,21493.336617,59467.996796,2

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2
0,V390000001S30010132000112,39,1,NaN,2,1955,1,1,4,1,1,2,2,1,2,1,1,2,-99,2,2,2,2,2,2,-88,1,1,2,2,1,1,5,1560.107273,2950.831036,-99
1,V390000001S30010930100112,39,1,NaN,2,1955,1,1,4,1,2,-99,4,1,2,-88,-88,-88,-88,-88,-88,-88,-88,2,1,-99,-88,-88,-88,-88,3,3,-88,2015.111681,1905.719622,-88
2,V390000001S96010845500122,39,1,NaN,2,1999,1,4,4,5,2,3,3,1,2,2,2,3,2,1,1,1,2,2,2,-88,1,1,2,2,1,2,3,2916.377523,8274.178438,1
3,V390000001S98010895010122,39,1,NaN,2,1935,1,1,7,1,1,2,3,1,2,1,1,1,1,1,1,2,1,2,2,-88,1,1,2,1,3,1,7,989.102446,2806.224527,2
4,V390000001S98010931110112,39,1,NaN,2,1969,1,2,4,3,2,2,2,1,2,3,3,1,1,2,1,1,2,2,1,2,3,1,2,3,1,2,4,786.707174,1488.000207,1

In [13]:
# Display shape of analysis dataframes
display(pulse2021_1q_analysis_df.shape)
display(pulse2021_2q_analysis_df.shape)
display(pulse2021_3q_analysis_df.shape)
display(pulse2021_4q_analysis_df.shape)

(77122, 29)

(78467, 35)

(59833, 36)

(57064, 36)

In [14]:
# Save first cut of analysis files to csv for review
#pulse2021_1q_analysis_df.to_csv('Resources/pulse2021_1q_analysis_df.csv', index=False)
#pulse2021_2q_analysis_df.to_csv('Resources/pulse2021_2q_analysis_df.csv', index=False)
#pulse2021_3q_analysis_df.to_csv('Resources/pulse2021_3q_analysis_df.csv', index=False)
#pulse2021_4q_analysis_df.to_csv('Resources/pulse2021_4q_analysis_df.csv', index=False)
#print("First cut of analysis files to csv for review have been saved")

In [15]:
# Create Restore point:  Make dataframe copies before cleaning
pulse2021_1q_analysis_wrk_df = pulse2021_1q_analysis_df.copy()
pulse2021_2q_analysis_wrk_df = pulse2021_2q_analysis_df.copy()
pulse2021_3q_analysis_wrk_df = pulse2021_3q_analysis_df.copy()
pulse2021_4q_analysis_wrk_df = pulse2021_4q_analysis_df.copy()
print("pulse2021 1q-4q analysis_df -- Restore point created")

pulse2021 1q-4q analysis_df -- Restore point created

In [16]:
# Display first 5 rows of analysis work dataframes
display(pulse2021_1q_analysis_wrk_df.head())
display(pulse2021_2q_analysis_wrk_df.head())
display(pulse2021_3q_analysis_wrk_df.head())
display(pulse2021_4q_analysis_wrk_df.head())

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER
0,V240000001S30011152510122,24,1,NaN,2,1957,1,1,3,1,2,2,2,2,1,1,2,2,-88,2,1,2,2,1,1,3,3263.656263,6298.128284,2
1,V240000001S33011384810122,24,1,NaN,2,1977,1,1,6,3,2,2,2,1,1,1,1,1,2,1,1,2,2,1,2,4,1751.171303,3379.369831,1
2,V240000001S34010333300122,24,1,NaN,2,1944,1,1,4,1,2,1,2,1,1,1,1,2,-88,2,1,2,1,3,1,2,1488.642062,1436.373490,2
3,V240000001S37010409600112,24,1,NaN,2,1947,1,1,6,2,1,2,2,-88,-88,-88,-88,2,-88,2,2,2,-88,3,3,-88,655.744049,632.719841,2
4,V240000001S37010979700122,24,1,NaN,2,1978,1,4,4,1,4,2,2,-88,-88,-88,-88,1,2,4,-88,-88,-88,3,3,-88,3569.279242,6887.912432,1

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,TW_YN
0,V290000001S18010005900121,29,1,NaN,2,1977,1,1,7,1,4,1,2,-88,-88,-88,-88,-88,-88,-88,-88,2,1,2,4,2,-88,-88,3,3,-88,828.050575,1565.261005,2,1
1,V290000001S30010947000111,29,1,NaN,2,1952,1,1,7,1,4,2,2,1,1,1,1,1,1,1,1,2,2,-88,1,1,2,1,1,1,7,778.499706,2207.392766,1,2
2,V290000001S30011651510121,29,1,NaN,2,2000,1,1,4,5,2,1,1,1,1,1,1,-88,-88,-88,-88,2,1,3,1,1,2,-88,3,3,-88,3510.046226,6635.027677,2,2
3,V290000001S31011267510121,29,1,NaN,2,1965,1,1,4,4,1,1,2,-88,-88,-88,-88,-88,-88,-88,-88,2,2,-88,2,2,2,-88,3,3,-88,845.921367,799.521050,2,2
4,V290000001S34010044300121,29,1,NaN,2,1948,1,1,3,2,1,1,2,1,1,1,1,2,1,2,1,2,2,-88,1,1,2,3,3,1,3,7376.505002,6971.890353,1,2

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2
0,V380000001,38,28,NaN,2,1965,1,1,6,5,1,2,1,1,2,2,1,2,2,2,1,1,2,2,1,2,1,1,2,2,1,2,6,662.915385,636.350100,1
1,V380000002,38,35,NaN,4,1952,1,1,4,1,2,2,2,1,2,1,1,1,1,2,1,1,1,2,1,4,1,1,2,1,1,1,5,536.164089,1046.123591,1
2,V380000003,38,2,NaN,4,1954,1,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,2,2,2,-88,1,1,2,1,1,1,4,399.481562,385.689765,-99
3,V380000004,38,55,NaN,3,1945,1,1,3,1,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,-88,1,1,2,1,1,1,-88,6385.449077,11877.653310,2
4,V380000005,38,42,NaN,1,1961,1,1,3,1,1,5,4,2,2,1,1,1,1,4,4,4,4,2,2,-88,3,1,2,-88,1,2,-88,21493.336617,59467.996796,2

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2
0,V390000001S30010132000112,39,1,NaN,2,1955,1,1,4,1,1,2,2,1,2,1,1,2,-99,2,2,2,2,2,2,-88,1,1,2,2,1,1,5,1560.107273,2950.831036,-99
1,V390000001S30010930100112,39,1,NaN,2,1955,1,1,4,1,2,-99,4,1,2,-88,-88,-88,-88,-88,-88,-88,-88,2,1,-99,-88,-88,-88,-88,3,3,-88,2015.111681,1905.719622,-88
2,V390000001S96010845500122,39,1,NaN,2,1999,1,4,4,5,2,3,3,1,2,2,2,3,2,1,1,1,2,2,2,-88,1,1,2,2,1,2,3,2916.377523,8274.178438,1
3,V390000001S98010895010122,39,1,NaN,2,1935,1,1,7,1,1,2,3,1,2,1,1,1,1,1,1,2,1,2,2,-88,1,1,2,1,3,1,7,989.102446,2806.224527,2
4,V390000001S98010931110112,39,1,NaN,2,1969,1,2,4,3,2,2,2,1,2,3,3,1,1,2,1,1,2,2,1,2,3,1,2,3,1,2,4,786.707174,1488.000207,1

### Clean data to make it consistent with other survey data for analysis

In [17]:
# Define clean_negative_values function to change -88 and -99 (No Response) to common response of 99 for analysis
def clean_negative_values(response):
    """Change -88 and -99 (No Response) to common response of 99"""

    if response in [-88, -99]:
        return 99
    else:
        return response

print("clean_negative_values function defined")

clean_negative_values function defined

In [18]:
# Get list of 1q file columns to identify which ones need the responses cleaned
pulse2021_1q_analysis_wrk_df.columns

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'TBIRTH_YEAR',
       'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC',
       'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'ANYWORK',
       'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH',
       'PUBHLTH', 'INCOME', 'HWEIGHT', 'PWEIGHT', 'EGENDER'],
      dtype='object')

In [19]:
# 1q file cleanup:  Replace all negative no response values (-88 and -99) with common value of 99 in dataframe
#                   using clean_negative_values function
clean_columns_list = ['TBIRTH_YEAR', 'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC',
                      'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF',
                      'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME', 'EGENDER']

for col in clean_columns_list:
    pulse2021_1q_analysis_wrk_df[col] = pulse2021_1q_analysis_wrk_df[col].apply(clean_negative_values)
    
# Confirm that no -88 or -99 values are in the dataframe
print("Checking to confirm that pulse2021_1q_analysis_wrk_df does not contain any -88 or -99 values")
negative_values_list = [-88, -99]
for response in negative_values_list:
    if response in pulse2021_1q_analysis_wrk_df.values:
        print(f"{response} exists in dataframe")
    else:
        print(f"{response} does not exist in dataframe")

Checking to confirm that pulse2021_1q_analysis_wrk_df does not contain any -88 or -99 values
-88 does not exist in dataframe
-99 does not exist in dataframe

In [20]:
# Get list of 2q file columns to identify which ones need the responses cleaned
pulse2021_2q_analysis_wrk_df.columns

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'TBIRTH_YEAR',
       'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC',
       'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING',
       'MOBILITY', 'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK',
       'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH',
       'INCOME', 'HWEIGHT', 'PWEIGHT', 'EGENDER', 'TW_YN'],
      dtype='object')

In [21]:
# 2q file cleanup:  Replace all negative no response values (-88 and -99) with common value of 99 in dataframe
#                   using clean_negative_values function
clean_columns_list = ['TBIRTH_YEAR', 'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC',
                      'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY',
                      'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD',
                      'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME', 'EGENDER', 'TW_YN']

for col in clean_columns_list:
    pulse2021_2q_analysis_wrk_df[col] = pulse2021_2q_analysis_wrk_df[col].apply(clean_negative_values)
    
# Confirm that no -88 or -99 values are in the dataframe
print("Checking to confirm that pulse2021_2q_analysis_wrk_df does not contain any -88 or -99 values")
negative_values_list = [-88, -99]
for response in negative_values_list:
    if response in pulse2021_2q_analysis_wrk_df.values:
        print(f"{response} exists in dataframe")
    else:
        print(f"{response} does not exist in dataframe")

Checking to confirm that pulse2021_2q_analysis_wrk_df does not contain any -88 or -99 values
-88 does not exist in dataframe
-99 does not exist in dataframe

In [22]:
# Get list of 3q file columns to identify which ones need the responses cleaned
pulse2021_3q_analysis_wrk_df.columns

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'TBIRTH_YEAR',
       'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'GENID_DESCRIBE',
       'SEXUAL_ORIENTATION', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID',
       'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY',
       'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF',
       'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME',
       'HWEIGHT', 'PWEIGHT', 'ACTIVITY2'],
      dtype='object')

In [23]:
# 3q file cleanup:  Replace all negative no response values (-88 and -99) with common value of 99 in dataframe
#                   using clean_negative_values function
clean_columns_list = ['TBIRTH_YEAR', 'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'GENID_DESCRIBE', 'SEXUAL_ORIENTATION',
                      'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING',
                      'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF',
                      'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME', 'ACTIVITY2']

for col in clean_columns_list:
    pulse2021_3q_analysis_wrk_df[col] = pulse2021_3q_analysis_wrk_df[col].apply(clean_negative_values)
    
# Confirm that no -88 or -99 values are in the dataframe
print("Checking to confirm that pulse2021_3q_analysis_wrk_df does not contain any -88 or -99 values")
negative_values_list = [-88, -99]
for response in negative_values_list:
    if response in pulse2021_3q_analysis_wrk_df.values:
        print(f"{response} exists in dataframe")
    else:
        print(f"{response} does not exist in dataframe")

Checking to confirm that pulse2021_3q_analysis_wrk_df does not contain any -88 or -99 values
-88 does not exist in dataframe
-99 does not exist in dataframe

In [24]:
# Get list of 4q file columns to identify which ones need the responses cleaned
pulse2021_4q_analysis_wrk_df.columns

Index(['SCRAM', 'WEEK', 'EST_ST', 'EST_MSA', 'REGION', 'TBIRTH_YEAR',
       'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'GENID_DESCRIBE',
       'SEXUAL_ORIENTATION', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID',
       'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY',
       'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF',
       'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME',
       'HWEIGHT', 'PWEIGHT', 'ACTIVITY2'],
      dtype='object')

In [25]:
# 4q file cleanup:  Replace all negative no response values (-88 and -99) with common value of 99 in dataframe
#                   using clean_negative_values function
clean_columns_list = ['TBIRTH_YEAR', 'RHISPANIC', 'RRACE', 'EEDUC', 'MS', 'GENID_DESCRIBE', 'SEXUAL_ORIENTATION',
                      'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING',
                      'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF',
                      'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME', 'ACTIVITY2']

for col in clean_columns_list:
    pulse2021_4q_analysis_wrk_df[col] = pulse2021_4q_analysis_wrk_df[col].apply(clean_negative_values)
    
# Confirm that no -88 or -99 values are in the dataframe
print("Checking to confirm that pulse2021_4q_analysis_wrk_df does not contain any -88 or -99 values")
negative_values_list = [-88, -99]
for response in negative_values_list:
    if response in pulse2021_4q_analysis_wrk_df.values:
        print(f"{response} exists in dataframe")
    else:
        print(f"{response} does not exist in dataframe")

Checking to confirm that pulse2021_4q_analysis_wrk_df does not contain any -88 or -99 values
-88 does not exist in dataframe
-99 does not exist in dataframe

In [26]:
# Add survey start and end date columns to quarterly dataframes
# 2021-1Q
pulse2021_1q_analysis_wrk_df['SURVEY_START_DATE'] = pd.to_datetime('2021-02-03')
pulse2021_1q_analysis_wrk_df['SURVEY_END_DATE'] = pd.to_datetime('2021-02-15')
# 2021-2Q
pulse2021_2q_analysis_wrk_df['SURVEY_START_DATE'] = pd.to_datetime('2021-04-28')
pulse2021_2q_analysis_wrk_df['SURVEY_END_DATE'] = pd.to_datetime('2021-05-10')
# 2021-3Q
pulse2021_3q_analysis_wrk_df['SURVEY_START_DATE'] = pd.to_datetime('2021-09-15')
pulse2021_3q_analysis_wrk_df['SURVEY_END_DATE'] = pd.to_datetime('2021-09-27')
# 2021-4Q
pulse2021_4q_analysis_wrk_df['SURVEY_START_DATE'] = pd.to_datetime('2021-09-29')
pulse2021_4q_analysis_wrk_df['SURVEY_END_DATE'] = pd.to_datetime('2021-10-11')
print("Survey start and end date columns added to quarterly surveys")

Survey start and end date columns added to quarterly surveys

In [27]:
# Add EST_MSA_CLEAN column to replace nulls in EST_MSA (Metropolitan Statistical Area) with 99999.9 to
# represent non-Metropolitan Statistical Areas
pulse2021_1q_analysis_wrk_df['EST_MSA_CLEAN'] = pulse2021_1q_analysis_wrk_df['EST_MSA'].fillna(99999.9)
pulse2021_2q_analysis_wrk_df['EST_MSA_CLEAN'] = pulse2021_2q_analysis_wrk_df['EST_MSA'].fillna(99999.9)
pulse2021_3q_analysis_wrk_df['EST_MSA_CLEAN'] = pulse2021_3q_analysis_wrk_df['EST_MSA'].fillna(99999.9)
pulse2021_4q_analysis_wrk_df['EST_MSA_CLEAN'] = pulse2021_4q_analysis_wrk_df['EST_MSA'].fillna(99999.9)
print("EST_MSA_CLEAN column added to quarterly dataframes")

EST_MSA_CLEAN column added to quarterly dataframes

In [28]:
# Display first 5 rows of 1q dataframe after columns added and before next round of cleaning
display('1q file after columns added and before next round of cleaning')
display(pulse2021_1q_analysis_wrk_df.head())

'1q file after columns added and before next round of cleaning'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN
0,V240000001S30011152510122,24,1,NaN,2,1957,1,1,3,1,2,2,2,2,1,1,2,2,99,2,1,2,2,1,1,3,3263.656263,6298.128284,2,2021-02-03,2021-02-15,99999.9
1,V240000001S33011384810122,24,1,NaN,2,1977,1,1,6,3,2,2,2,1,1,1,1,1,2,1,1,2,2,1,2,4,1751.171303,3379.369831,1,2021-02-03,2021-02-15,99999.9
2,V240000001S34010333300122,24,1,NaN,2,1944,1,1,4,1,2,1,2,1,1,1,1,2,99,2,1,2,1,3,1,2,1488.642062,1436.373490,2,2021-02-03,2021-02-15,99999.9
3,V240000001S37010409600112,24,1,NaN,2,1947,1,1,6,2,1,2,2,99,99,99,99,2,99,2,2,2,99,3,3,99,655.744049,632.719841,2,2021-02-03,2021-02-15,99999.9
4,V240000001S37010979700122,24,1,NaN,2,1978,1,4,4,1,4,2,2,99,99,99,99,1,2,4,99,99,99,3,3,99,3569.279242,6887.912432,1,2021-02-03,2021-02-15,99999.9

In [29]:
# 1q file cleanup: To maintain column alignment across all surveys, add missing survey columns
#                  with response set to 99 (No Response) because data was not collected at that time.
#                  The added columns will include '_PLUG' at the end of the column name.

# Note:  'EGENDER' will be renamed to 'GENID_DESCRIBE'

# Survey columns that are not in the 1q file:
plug_columns_list = ['LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
                     'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID', 'SEXUAL_ORIENTATION',
                     'ACTIVITY2', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV', 'TW_YN']

# Loop to add missing survey columns with response set to 99 (No Response) because data was not collected at that time
for col in plug_columns_list:
    pulse2021_1q_analysis_wrk_df[col +'_PLUG'] = 99

display('1q file after _PLUG columns added')
display(pulse2021_1q_analysis_wrk_df.head())

'1q file after _PLUG columns added'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG,SEXUAL_ORIENTATION_PLUG,ACTIVITY2_PLUG,SEEING_PLUG,HEARING_PLUG,MOBILITY_PLUG,REMEMBERING_PLUG,WRKLOSSRV_PLUG,TW_YN_PLUG
0,V240000001S30011152510122,24,1,NaN,2,1957,1,1,3,1,2,2,2,2,1,1,2,2,99,2,1,2,2,1,1,3,3263.656263,6298.128284,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V240000001S33011384810122,24,1,NaN,2,1977,1,1,6,3,2,2,2,1,1,1,1,1,2,1,1,2,2,1,2,4,1751.171303,3379.369831,1,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V240000001S34010333300122,24,1,NaN,2,1944,1,1,4,1,2,1,2,1,1,1,1,2,99,2,1,2,1,3,1,2,1488.642062,1436.373490,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V240000001S37010409600112,24,1,NaN,2,1947,1,1,6,2,1,2,2,99,99,99,99,2,99,2,2,2,99,3,3,99,655.744049,632.719841,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V240000001S37010979700122,24,1,NaN,2,1978,1,4,4,1,4,2,2,99,99,99,99,1,2,4,99,99,99,3,3,99,3569.279242,6887.912432,1,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99

In [30]:
# Display first 5 rows of 2q dataframe after columns added and before next round of cleaning
display('2q file after columns added and before next round of cleaning')
display(pulse2021_2q_analysis_wrk_df.head())

'2q file after columns added and before next round of cleaning'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,TW_YN,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN
0,V290000001S18010005900121,29,1,NaN,2,1977,1,1,7,1,4,1,2,99,99,99,99,99,99,99,99,2,1,2,4,2,99,99,3,3,99,828.050575,1565.261005,2,1,2021-04-28,2021-05-10,99999.9
1,V290000001S30010947000111,29,1,NaN,2,1952,1,1,7,1,4,2,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,7,778.499706,2207.392766,1,2,2021-04-28,2021-05-10,99999.9
2,V290000001S30011651510121,29,1,NaN,2,2000,1,1,4,5,2,1,1,1,1,1,1,99,99,99,99,2,1,3,1,1,2,99,3,3,99,3510.046226,6635.027677,2,2,2021-04-28,2021-05-10,99999.9
3,V290000001S31011267510121,29,1,NaN,2,1965,1,1,4,4,1,1,2,99,99,99,99,99,99,99,99,2,2,99,2,2,2,99,3,3,99,845.921367,799.521050,2,2,2021-04-28,2021-05-10,99999.9
4,V290000001S34010044300121,29,1,NaN,2,1948,1,1,3,2,1,1,2,1,1,1,1,2,1,2,1,2,2,99,1,1,2,3,3,1,3,7376.505002,6971.890353,1,2,2021-04-28,2021-05-10,99999.9

In [31]:
# 2q file cleanup: To maintain column alignment across all surveys, add missing survey columns
#                  with response set to 99 (No Response) because data was not collected at that time.
#                  The added columns will include '_PLUG' at the end of the column name.

# Note:  'EGENDER' will be renamed to 'GENID_DESCRIBE'

# Survey columns that are not in the 2q file:
plug_columns_list = ['LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
                     'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID', 'SEXUAL_ORIENTATION',
                     'ACTIVITY2']

# Loop to add missing survey columns with response set to 99 (No Response) because data was not collected at that time
for col in plug_columns_list:
    pulse2021_2q_analysis_wrk_df[col +'_PLUG'] = 99

display('2q file after _PLUG columns added')
display(pulse2021_2q_analysis_wrk_df.head())

'2q file after _PLUG columns added'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,TW_YN,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG,SEXUAL_ORIENTATION_PLUG,ACTIVITY2_PLUG
0,V290000001S18010005900121,29,1,NaN,2,1977,1,1,7,1,4,1,2,99,99,99,99,99,99,99,99,2,1,2,4,2,99,99,3,3,99,828.050575,1565.261005,2,1,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V290000001S30010947000111,29,1,NaN,2,1952,1,1,7,1,4,2,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,7,778.499706,2207.392766,1,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V290000001S30011651510121,29,1,NaN,2,2000,1,1,4,5,2,1,1,1,1,1,1,99,99,99,99,2,1,3,1,1,2,99,3,3,99,3510.046226,6635.027677,2,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V290000001S31011267510121,29,1,NaN,2,1965,1,1,4,4,1,1,2,99,99,99,99,99,99,99,99,2,2,99,2,2,2,99,3,3,99,845.921367,799.521050,2,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V290000001S34010044300121,29,1,NaN,2,1948,1,1,3,2,1,1,2,1,1,1,1,2,1,2,1,2,2,99,1,1,2,3,3,1,3,7376.505002,6971.890353,1,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99

In [32]:
# Display first 5 rows of 3q dataframe after columns added and before next round of cleaning
display('3q file after columns added and before next round of cleaning')
display(pulse2021_3q_analysis_wrk_df.head())

'3q file after columns added and before next round of cleaning'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN
0,V380000001,38,28,NaN,2,1965,1,1,6,5,1,2,1,1,2,2,1,2,2,2,1,1,2,2,1,2,1,1,2,2,1,2,6,662.915385,636.350100,1,2021-09-15,2021-09-27,99999.9
1,V380000002,38,35,NaN,4,1952,1,1,4,1,2,2,2,1,2,1,1,1,1,2,1,1,1,2,1,4,1,1,2,1,1,1,5,536.164089,1046.123591,1,2021-09-15,2021-09-27,99999.9
2,V380000003,38,2,NaN,4,1954,1,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,2,2,2,99,1,1,2,1,1,1,4,399.481562,385.689765,99,2021-09-15,2021-09-27,99999.9
3,V380000004,38,55,NaN,3,1945,1,1,3,1,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,99,6385.449077,11877.653310,2,2021-09-15,2021-09-27,99999.9
4,V380000005,38,42,NaN,1,1961,1,1,3,1,1,5,4,2,2,1,1,1,1,4,4,4,4,2,2,99,3,1,2,99,1,2,99,21493.336617,59467.996796,2,2021-09-15,2021-09-27,99999.9

In [33]:
# 3q file cleanup: To maintain column alignment across all surveys, add missing survey columns
#                  with response set to 99 (No Response) because data was not collected at that time.
#                  The added columns will include '_PLUG' at the end of the column name.

# Note:  'EGENDER' will be renamed to 'GENID_DESCRIBE'

# Survey columns that are not in the 3q file:
plug_columns_list = ['LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
                     'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID']

# Loop to add missing survey columns with response set to 99 (No Response) because data was not collected at that time
for col in plug_columns_list:
    pulse2021_3q_analysis_wrk_df[col +'_PLUG'] = 99

display('3q file after _PLUG columns added')
display(pulse2021_3q_analysis_wrk_df.head())

'3q file after _PLUG columns added'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG
0,V380000001,38,28,NaN,2,1965,1,1,6,5,1,2,1,1,2,2,1,2,2,2,1,1,2,2,1,2,1,1,2,2,1,2,6,662.915385,636.350100,1,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V380000002,38,35,NaN,4,1952,1,1,4,1,2,2,2,1,2,1,1,1,1,2,1,1,1,2,1,4,1,1,2,1,1,1,5,536.164089,1046.123591,1,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V380000003,38,2,NaN,4,1954,1,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,2,2,2,99,1,1,2,1,1,1,4,399.481562,385.689765,99,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V380000004,38,55,NaN,3,1945,1,1,3,1,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,99,6385.449077,11877.653310,2,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V380000005,38,42,NaN,1,1961,1,1,3,1,1,5,4,2,2,1,1,1,1,4,4,4,4,2,2,99,3,1,2,99,1,2,99,21493.336617,59467.996796,2,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99

In [34]:
# Display first 5 rows of 4q dataframe after columns added and before next round of cleaning
display('4q file after columns added and before next round of cleaning')
display(pulse2021_4q_analysis_wrk_df.head())

'4q file after columns added and before next round of cleaning'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN
0,V390000001S30010132000112,39,1,NaN,2,1955,1,1,4,1,1,2,2,1,2,1,1,2,99,2,2,2,2,2,2,99,1,1,2,2,1,1,5,1560.107273,2950.831036,99,2021-09-29,2021-10-11,99999.9
1,V390000001S30010930100112,39,1,NaN,2,1955,1,1,4,1,2,99,4,1,2,99,99,99,99,99,99,99,99,2,1,99,99,99,99,99,3,3,99,2015.111681,1905.719622,99,2021-09-29,2021-10-11,99999.9
2,V390000001S96010845500122,39,1,NaN,2,1999,1,4,4,5,2,3,3,1,2,2,2,3,2,1,1,1,2,2,2,99,1,1,2,2,1,2,3,2916.377523,8274.178438,1,2021-09-29,2021-10-11,99999.9
3,V390000001S98010895010122,39,1,NaN,2,1935,1,1,7,1,1,2,3,1,2,1,1,1,1,1,1,2,1,2,2,99,1,1,2,1,3,1,7,989.102446,2806.224527,2,2021-09-29,2021-10-11,99999.9
4,V390000001S98010931110112,39,1,NaN,2,1969,1,2,4,3,2,2,2,1,2,3,3,1,1,2,1,1,2,2,1,2,3,1,2,3,1,2,4,786.707174,1488.000207,1,2021-09-29,2021-10-11,99999.9

In [35]:
# 4q file cleanup: To maintain column alignment across all surveys, add missing survey columns
#                  with response set to 99 (No Response) because data was not collected at that time.
#                  The added columns will include '_PLUG' at the end of the column name.

# Note:  'EGENDER' will be renamed to 'GENID_DESCRIBE'

# Survey columns that are not in the 4q file:
plug_columns_list = ['LONGCOVID', 'SYMPTMIMPCT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN',
                     'TWDAYS', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'WHENCOVID']

# Loop to add missing survey columns with response set to 99 (No Response) because data was not collected at that time
for col in plug_columns_list:
    pulse2021_4q_analysis_wrk_df[col +'_PLUG'] = 99

display('4q file after _PLUG columns added')
display(pulse2021_4q_analysis_wrk_df.head())

'4q file after _PLUG columns added'

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG
0,V390000001S30010132000112,39,1,NaN,2,1955,1,1,4,1,1,2,2,1,2,1,1,2,99,2,2,2,2,2,2,99,1,1,2,2,1,1,5,1560.107273,2950.831036,99,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V390000001S30010930100112,39,1,NaN,2,1955,1,1,4,1,2,99,4,1,2,99,99,99,99,99,99,99,99,2,1,99,99,99,99,99,3,3,99,2015.111681,1905.719622,99,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V390000001S96010845500122,39,1,NaN,2,1999,1,4,4,5,2,3,3,1,2,2,2,3,2,1,1,1,2,2,2,99,1,1,2,2,1,2,3,2916.377523,8274.178438,1,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V390000001S98010895010122,39,1,NaN,2,1935,1,1,7,1,1,2,3,1,2,1,1,1,1,1,1,2,1,2,2,99,1,1,2,1,3,1,7,989.102446,2806.224527,2,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V390000001S98010931110112,39,1,NaN,2,1969,1,2,4,3,2,2,2,1,2,3,3,1,1,2,1,1,2,2,1,2,3,1,2,3,1,2,4,786.707174,1488.000207,1,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99

In [36]:
# Display shape of updated dataframes
display(pulse2021_1q_analysis_wrk_df.shape)
display(pulse2021_2q_analysis_wrk_df.shape)
display(pulse2021_3q_analysis_wrk_df.shape)
display(pulse2021_4q_analysis_wrk_df.shape)

(77122, 53)

(78467, 53)

(59833, 52)

(57064, 52)

In [37]:
# Save cleaned files to csv for review, if needed
#pulse2021_1q_analysis_wrk_df.to_csv('Resources/pulse2021_1q_analysis_wrk_df.csv', index=False)
#pulse2021_2q_analysis_wrk_df.to_csv('Resources/pulse2021_2q_analysis_wrk_df.csv', index=False)
#pulse2021_3q_analysis_wrk_df.to_csv('Resources/pulse2021_3q_analysis_wrk_df.csv', index=False)
#pulse2021_4q_analysis_wrk_df.to_csv('Resources/pulse2021_4q_analysis_wrk_df.csv', index=False)
#print("Cleaned files have been saved")

In [38]:
# Create Restore point:  Make dataframe copies after cleaning
pulse2021_1q_analysis_clean_df = pulse2021_1q_analysis_wrk_df.copy()
pulse2021_2q_analysis_clean_df = pulse2021_2q_analysis_wrk_df.copy()
pulse2021_3q_analysis_clean_df = pulse2021_3q_analysis_wrk_df.copy()
pulse2021_4q_analysis_clean_df = pulse2021_4q_analysis_wrk_df.copy()
print("pulse2021 1q-4q analysis_wrk_df -- Restore point has been created")

pulse2021 1q-4q analysis_wrk_df -- Restore point has been created

In [39]:
# Display first 5 rows of analysis cleaned dataframes
display(pulse2021_1q_analysis_clean_df.head())
display(pulse2021_2q_analysis_clean_df.head())
display(pulse2021_3q_analysis_clean_df.head())
display(pulse2021_4q_analysis_clean_df.head())

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG,SEXUAL_ORIENTATION_PLUG,ACTIVITY2_PLUG,SEEING_PLUG,HEARING_PLUG,MOBILITY_PLUG,REMEMBERING_PLUG,WRKLOSSRV_PLUG,TW_YN_PLUG
0,V240000001S30011152510122,24,1,NaN,2,1957,1,1,3,1,2,2,2,2,1,1,2,2,99,2,1,2,2,1,1,3,3263.656263,6298.128284,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V240000001S33011384810122,24,1,NaN,2,1977,1,1,6,3,2,2,2,1,1,1,1,1,2,1,1,2,2,1,2,4,1751.171303,3379.369831,1,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V240000001S34010333300122,24,1,NaN,2,1944,1,1,4,1,2,1,2,1,1,1,1,2,99,2,1,2,1,3,1,2,1488.642062,1436.373490,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V240000001S37010409600112,24,1,NaN,2,1947,1,1,6,2,1,2,2,99,99,99,99,2,99,2,2,2,99,3,3,99,655.744049,632.719841,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V240000001S37010979700122,24,1,NaN,2,1978,1,4,4,1,4,2,2,99,99,99,99,1,2,4,99,99,99,3,3,99,3569.279242,6887.912432,1,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,EGENDER,TW_YN,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG,SEXUAL_ORIENTATION_PLUG,ACTIVITY2_PLUG
0,V290000001S18010005900121,29,1,NaN,2,1977,1,1,7,1,4,1,2,99,99,99,99,99,99,99,99,2,1,2,4,2,99,99,3,3,99,828.050575,1565.261005,2,1,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V290000001S30010947000111,29,1,NaN,2,1952,1,1,7,1,4,2,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,7,778.499706,2207.392766,1,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V290000001S30011651510121,29,1,NaN,2,2000,1,1,4,5,2,1,1,1,1,1,1,99,99,99,99,2,1,3,1,1,2,99,3,3,99,3510.046226,6635.027677,2,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V290000001S31011267510121,29,1,NaN,2,1965,1,1,4,4,1,1,2,99,99,99,99,99,99,99,99,2,2,99,2,2,2,99,3,3,99,845.921367,799.521050,2,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V290000001S34010044300121,29,1,NaN,2,1948,1,1,3,2,1,1,2,1,1,1,1,2,1,2,1,2,2,99,1,1,2,3,3,1,3,7376.505002,6971.890353,1,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG
0,V380000001,38,28,NaN,2,1965,1,1,6,5,1,2,1,1,2,2,1,2,2,2,1,1,2,2,1,2,1,1,2,2,1,2,6,662.915385,636.350100,1,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V380000002,38,35,NaN,4,1952,1,1,4,1,2,2,2,1,2,1,1,1,1,2,1,1,1,2,1,4,1,1,2,1,1,1,5,536.164089,1046.123591,1,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V380000003,38,2,NaN,4,1954,1,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,2,2,2,99,1,1,2,1,1,1,4,399.481562,385.689765,99,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V380000004,38,55,NaN,3,1945,1,1,3,1,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,99,6385.449077,11877.653310,2,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V380000005,38,42,NaN,1,1961,1,1,3,1,1,5,4,2,2,1,1,1,1,4,4,4,4,2,2,99,3,1,2,99,1,2,99,21493.336617,59467.996796,2,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99

,SCRAM,WEEK,EST_ST,EST_MSA,REGION,TBIRTH_YEAR,RHISPANIC,RRACE,EEDUC,MS,GENID_DESCRIBE,SEXUAL_ORIENTATION,THHLD_NUMPER,RECVDVACC,HADCOVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,WRKLOSSRV,ANYWORK,KINDWORK,EXPNS_DIF,CURFOODSUF,FREEFOOD,TENURE,PRIVHLTH,PUBHLTH,INCOME,HWEIGHT,PWEIGHT,ACTIVITY2,SURVEY_START_DATE,SURVEY_END_DATE,EST_MSA_CLEAN,LONGCOVID_PLUG,SYMPTMIMPCT_PLUG,SELFCARE_PLUG,UNDERSTAND_PLUG,PRICECHNG_PLUG,PRICESTRESS_PLUG,PRICECONCRN_PLUG,TWDAYS_PLUG,TSPNDFOOD_PLUG,TSPNDPRPD_PLUG,ND_DISPLACE_PLUG,MEDICAID_PLUG,WHENCOVID_PLUG
0,V390000001S30010132000112,39,1,NaN,2,1955,1,1,4,1,1,2,2,1,2,1,1,2,99,2,2,2,2,2,2,99,1,1,2,2,1,1,5,1560.107273,2950.831036,99,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V390000001S30010930100112,39,1,NaN,2,1955,1,1,4,1,2,99,4,1,2,99,99,99,99,99,99,99,99,2,1,99,99,99,99,99,3,3,99,2015.111681,1905.719622,99,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V390000001S96010845500122,39,1,NaN,2,1999,1,4,4,5,2,3,3,1,2,2,2,3,2,1,1,1,2,2,2,99,1,1,2,2,1,2,3,2916.377523,8274.178438,1,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V390000001S98010895010122,39,1,NaN,2,1935,1,1,7,1,1,2,3,1,2,1,1,1,1,1,1,2,1,2,2,99,1,1,2,1,3,1,7,989.102446,2806.224527,2,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V390000001S98010931110112,39,1,NaN,2,1969,1,2,4,3,2,2,2,1,2,3,3,1,1,2,1,1,2,2,1,2,3,1,2,3,1,2,4,786.707174,1488.000207,1,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99

### Align dataframes on fields that will be used for analysis and concatenate to create 2021 data file that will be used for analysis.

In [40]:
# Drop 'EST_MSA' column from all dataframes 'EST_MSA_CLEAN' column will be used for analysis
pulse2021_1q_analysis_clean_df = pulse2021_1q_analysis_clean_df.drop(['EST_MSA'], axis=1)
pulse2021_2q_analysis_clean_df = pulse2021_2q_analysis_clean_df.drop(['EST_MSA'], axis=1)
pulse2021_3q_analysis_clean_df = pulse2021_3q_analysis_clean_df.drop(['EST_MSA'], axis=1)
pulse2021_4q_analysis_clean_df = pulse2021_4q_analysis_clean_df.drop(['EST_MSA'], axis=1)
print(" EST_MSA column dropped from pulse2021 1q_4q analysis_clean_df dataframes")

 EST_MSA column dropped from pulse2021 1q_4q analysis_clean_df dataframes

In [41]:
# Display 1q dataframe columns to determine which columns to rename
display("pulse2021_1q_analysis_clean_df columns before rename")
display(pulse2021_1q_analysis_clean_df.columns)

'pulse2021_1q_analysis_clean_df columns before rename'

Index(['SCRAM', 'WEEK', 'EST_ST', 'REGION', 'TBIRTH_YEAR', 'RHISPANIC',
       'RRACE', 'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID',
       'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'ANYWORK', 'KINDWORK',
       'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH',
       'INCOME', 'HWEIGHT', 'PWEIGHT', 'EGENDER', 'SURVEY_START_DATE',
       'SURVEY_END_DATE', 'EST_MSA_CLEAN', 'LONGCOVID_PLUG',
       'SYMPTMIMPCT_PLUG', 'SELFCARE_PLUG', 'UNDERSTAND_PLUG',
       'PRICECHNG_PLUG', 'PRICESTRESS_PLUG', 'PRICECONCRN_PLUG', 'TWDAYS_PLUG',
       'TSPNDFOOD_PLUG', 'TSPNDPRPD_PLUG', 'ND_DISPLACE_PLUG', 'MEDICAID_PLUG',
       'WHENCOVID_PLUG', 'SEXUAL_ORIENTATION_PLUG', 'ACTIVITY2_PLUG',
       'SEEING_PLUG', 'HEARING_PLUG', 'MOBILITY_PLUG', 'REMEMBERING_PLUG',
       'WRKLOSSRV_PLUG', 'TW_YN_PLUG'],
      dtype='object')

In [42]:
# Rename 1q dataframe columns to make them easier to understand and align with other quarter files
pulse2021_1q_analysis_clean_df.columns = ['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC',
                                          'RACE', 'EDUCATION', 'MARITAL_STATUS', 'TOTAL_HOUSEHOLD',
                                          'RECVD_VAC', 'HAD_COVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN',
                                          'EMPLOYED', 'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD',
                                          'OWN_RENT', 'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME', 'HWEIGHT', 'PWEIGHT',
                                          'GENDER_IDENITY', 'SURVEY_START_DATE', 'SURVEY_END_DATE', 'METRO_AREA',
                                          'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE', 'UNDERSTAND', 'PRICECHNG',
                                          'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE', 'TSPNDFOOD', 'TSPNDPRPD',
                                          'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN', 'SEXUAL_ORIENTATION',
                                          'ACTIVITY2_PLUG', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
                                          'JOBLOSS', 'TW_YN_PLUG']
                                        
#Drop 'ACTIVITY2_PLUG' and 'TW_YN_PLUG' columns until we decide they needed for our analysis
pulse2021_1q_analysis_clean_df = pulse2021_1q_analysis_clean_df.drop(['ACTIVITY2_PLUG'], axis=1)
pulse2021_1q_analysis_clean_df = pulse2021_1q_analysis_clean_df.drop(['TW_YN_PLUG'], axis=1)

display("pulse2021_1q_analysis_clean_df columns after rename and drop of ACTIVITY2_PLUG and TW_YN_PLUG columns")
display(pulse2021_1q_analysis_clean_df.columns)
display(pulse2021_1q_analysis_clean_df.head())
display(pulse2021_1q_analysis_clean_df.shape)

'pulse2021_1q_analysis_clean_df columns after rename and drop of ACTIVITY2_PLUG and TW_YN_PLUG columns'

Index(['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC', 'RACE',
       'EDUCATION', 'MARITAL_STATUS', 'TOTAL_HOUSEHOLD', 'RECVD_VAC',
       'HAD_COVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'EMPLOYED',
       'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD', 'OWN_RENT',
       'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME', 'HWEIGHT', 'PWEIGHT',
       'GENDER_IDENITY', 'SURVEY_START_DATE', 'SURVEY_END_DATE', 'METRO_AREA',
       'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE', 'UNDERSTAND',
       'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE', 'TSPNDFOOD',
       'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN',
       'SEXUAL_ORIENTATION', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
       'JOBLOSS'],
      dtype='object')

,SCRAM,WEEK,STATE,REGION,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,TOTAL_HOUSEHOLD,RECVD_VAC,HAD_COVID,ANXIOUS,WORRY,INTEREST,DOWN,EMPLOYED,WORK_SECTOR,EXPNS_DIF,CURFOODSUF,REC_FREEFOOD,OWN_RENT,PRIVHLTH_INS,PUBHLTH_INS,INCOME,HWEIGHT,PWEIGHT,GENDER_IDENITY,SURVEY_START_DATE,SURVEY_END_DATE,METRO_AREA,LONG_COVID,LONG_COVID_IMPACT,SELFCARE,UNDERSTAND,PRICECHNG,PRICESTRESS,PRICECONCRN,WORK_REMOTE,TSPNDFOOD,TSPNDPRPD,ND_DISPLACE,MEDICAID,HAD_COVID_WHEN,SEXUAL_ORIENTATION,SEEING,HEARING,MOBILITY,REMEMBERING,JOBLOSS
0,V240000001S30011152510122,24,1,2,1957,1,1,3,1,2,2,2,2,1,1,2,2,99,2,1,2,2,1,1,3,3263.656263,6298.128284,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V240000001S33011384810122,24,1,2,1977,1,1,6,3,2,2,2,1,1,1,1,1,2,1,1,2,2,1,2,4,1751.171303,3379.369831,1,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V240000001S34010333300122,24,1,2,1944,1,1,4,1,2,1,2,1,1,1,1,2,99,2,1,2,1,3,1,2,1488.642062,1436.373490,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V240000001S37010409600112,24,1,2,1947,1,1,6,2,1,2,2,99,99,99,99,2,99,2,2,2,99,3,3,99,655.744049,632.719841,2,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V240000001S37010979700122,24,1,2,1978,1,4,4,1,4,2,2,99,99,99,99,1,2,4,99,99,99,3,3,99,3569.279242,6887.912432,1,2021-02-03,2021-02-15,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99

(77122, 50)

In [43]:
# Display 2q dataframe columns to determine which columns to rename
display("pulse2021_2q_analysis_clean_df columns before rename")
display(pulse2021_2q_analysis_clean_df.columns)

'pulse2021_2q_analysis_clean_df columns before rename'

Index(['SCRAM', 'WEEK', 'EST_ST', 'REGION', 'TBIRTH_YEAR', 'RHISPANIC',
       'RRACE', 'EEDUC', 'MS', 'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID',
       'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY',
       'REMEMBERING', 'WRKLOSSRV', 'ANYWORK', 'KINDWORK', 'EXPNS_DIF',
       'CURFOODSUF', 'FREEFOOD', 'TENURE', 'PRIVHLTH', 'PUBHLTH', 'INCOME',
       'HWEIGHT', 'PWEIGHT', 'EGENDER', 'TW_YN', 'SURVEY_START_DATE',
       'SURVEY_END_DATE', 'EST_MSA_CLEAN', 'LONGCOVID_PLUG',
       'SYMPTMIMPCT_PLUG', 'SELFCARE_PLUG', 'UNDERSTAND_PLUG',
       'PRICECHNG_PLUG', 'PRICESTRESS_PLUG', 'PRICECONCRN_PLUG', 'TWDAYS_PLUG',
       'TSPNDFOOD_PLUG', 'TSPNDPRPD_PLUG', 'ND_DISPLACE_PLUG', 'MEDICAID_PLUG',
       'WHENCOVID_PLUG', 'SEXUAL_ORIENTATION_PLUG', 'ACTIVITY2_PLUG'],
      dtype='object')

In [44]:
# Rename 2q dataframe columns to make them easier to understand and align with other quarter files
pulse2021_2q_analysis_clean_df.columns = ['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC',
                                          'RACE', 'EDUCATION', 'MARITAL_STATUS', 'TOTAL_HOUSEHOLD',
                                          'RECVD_VAC', 'HAD_COVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN',
                                          'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
                                          'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD',
                                          'OWN_RENT', 'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME', 'HWEIGHT', 'PWEIGHT',
                                          'GENDER_IDENITY', 'TW_YN' , 'SURVEY_START_DATE', 'SURVEY_END_DATE',
                                          'METRO_AREA', 'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE', 'UNDERSTAND',
                                          'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE', 'TSPNDFOOD',
                                          'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN', 'SEXUAL_ORIENTATION',
                                          'ACTIVITY2_PLUG']

#Drop 'ACTIVITY2_PLUG' and 'TW_YN' columns until we decide they needed for our analysis
pulse2021_2q_analysis_clean_df = pulse2021_2q_analysis_clean_df.drop(['ACTIVITY2_PLUG'], axis=1)
pulse2021_2q_analysis_clean_df = pulse2021_2q_analysis_clean_df.drop(['TW_YN'], axis=1)

display("pulse2021_2q_analysis_clean_df columns after rename and drop of ACTIVITY2_PLUG and TW_YN columns")
display(pulse2021_2q_analysis_clean_df.columns)
display(pulse2021_2q_analysis_clean_df.head())
display(pulse2021_2q_analysis_clean_df.shape)

'pulse2021_2q_analysis_clean_df columns after rename and drop of ACTIVITY2_PLUG and TW_YN columns'

Index(['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC', 'RACE',
       'EDUCATION', 'MARITAL_STATUS', 'TOTAL_HOUSEHOLD', 'RECVD_VAC',
       'HAD_COVID', 'ANXIOUS', 'WORRY', 'INTEREST', 'DOWN', 'SEEING',
       'HEARING', 'MOBILITY', 'REMEMBERING', 'JOBLOSS', 'EMPLOYED',
       'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD', 'OWN_RENT',
       'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME', 'HWEIGHT', 'PWEIGHT',
       'GENDER_IDENITY', 'SURVEY_START_DATE', 'SURVEY_END_DATE', 'METRO_AREA',
       'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE', 'UNDERSTAND',
       'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE', 'TSPNDFOOD',
       'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN',
       'SEXUAL_ORIENTATION'],
      dtype='object')

,SCRAM,WEEK,STATE,REGION,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,TOTAL_HOUSEHOLD,RECVD_VAC,HAD_COVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,JOBLOSS,EMPLOYED,WORK_SECTOR,EXPNS_DIF,CURFOODSUF,REC_FREEFOOD,OWN_RENT,PRIVHLTH_INS,PUBHLTH_INS,INCOME,HWEIGHT,PWEIGHT,GENDER_IDENITY,SURVEY_START_DATE,SURVEY_END_DATE,METRO_AREA,LONG_COVID,LONG_COVID_IMPACT,SELFCARE,UNDERSTAND,PRICECHNG,PRICESTRESS,PRICECONCRN,WORK_REMOTE,TSPNDFOOD,TSPNDPRPD,ND_DISPLACE,MEDICAID,HAD_COVID_WHEN,SEXUAL_ORIENTATION
0,V290000001S18010005900121,29,1,2,1977,1,1,7,1,4,1,2,99,99,99,99,99,99,99,99,2,1,2,4,2,99,99,3,3,99,828.050575,1565.261005,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V290000001S30010947000111,29,1,2,1952,1,1,7,1,4,2,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,7,778.499706,2207.392766,1,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V290000001S30011651510121,29,1,2,2000,1,1,4,5,2,1,1,1,1,1,1,99,99,99,99,2,1,3,1,1,2,99,3,3,99,3510.046226,6635.027677,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V290000001S31011267510121,29,1,2,1965,1,1,4,4,1,1,2,99,99,99,99,99,99,99,99,2,2,99,2,2,2,99,3,3,99,845.921367,799.521050,2,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V290000001S34010044300121,29,1,2,1948,1,1,3,2,1,1,2,1,1,1,1,2,1,2,1,2,2,99,1,1,2,3,3,1,3,7376.505002,6971.890353,1,2021-04-28,2021-05-10,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99,99

(78467, 50)

In [45]:
# Display 3q dataframe columns to determine which columns to rename
display("pulse2021_3q_analysis_clean_df columns before rename")
display(pulse2021_3q_analysis_clean_df.columns)

'pulse2021_3q_analysis_clean_df columns before rename'

Index(['SCRAM', 'WEEK', 'EST_ST', 'REGION', 'TBIRTH_YEAR', 'RHISPANIC',
       'RRACE', 'EEDUC', 'MS', 'GENID_DESCRIBE', 'SEXUAL_ORIENTATION',
       'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST',
       'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV',
       'ANYWORK', 'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE',
       'PRIVHLTH', 'PUBHLTH', 'INCOME', 'HWEIGHT', 'PWEIGHT', 'ACTIVITY2',
       'SURVEY_START_DATE', 'SURVEY_END_DATE', 'EST_MSA_CLEAN',
       'LONGCOVID_PLUG', 'SYMPTMIMPCT_PLUG', 'SELFCARE_PLUG',
       'UNDERSTAND_PLUG', 'PRICECHNG_PLUG', 'PRICESTRESS_PLUG',
       'PRICECONCRN_PLUG', 'TWDAYS_PLUG', 'TSPNDFOOD_PLUG', 'TSPNDPRPD_PLUG',
       'ND_DISPLACE_PLUG', 'MEDICAID_PLUG', 'WHENCOVID_PLUG'],
      dtype='object')

In [46]:
# Rename 3q dataframe columns to make them easier to understand and align with other quarter files
pulse2021_3q_analysis_clean_df.columns = ['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC',
                                          'RACE', 'EDUCATION', 'MARITAL_STATUS', 'GENDER_IDENITY', 'SEXUAL_ORIENTATION',
                                          'TOTAL_HOUSEHOLD', 'RECVD_VAC', 'HAD_COVID', 'ANXIOUS', 'WORRY', 'INTEREST',
                                          'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
                                          'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD',
                                          'OWN_RENT', 'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME', 'HWEIGHT', 'PWEIGHT',
                                          'ACTIVITY2', 'SURVEY_START_DATE', 'SURVEY_END_DATE',
                                          'METRO_AREA', 'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE', 'UNDERSTAND',
                                          'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE', 'TSPNDFOOD',
                                          'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN'] 

#Drop 'ACTIVITY2' columns until we decide if needed for our analysis
pulse2021_3q_analysis_clean_df = pulse2021_3q_analysis_clean_df.drop(['ACTIVITY2'], axis=1)

display("pulse2021_3q_analysis_clean_df columns after rename and drop of ACTIVITY2 column")
display(pulse2021_3q_analysis_clean_df.columns)
display(pulse2021_3q_analysis_clean_df.head())
display(pulse2021_3q_analysis_clean_df.shape)

'pulse2021_3q_analysis_clean_df columns after rename and drop of ACTIVITY2 column'

Index(['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC', 'RACE',
       'EDUCATION', 'MARITAL_STATUS', 'GENDER_IDENITY', 'SEXUAL_ORIENTATION',
       'TOTAL_HOUSEHOLD', 'RECVD_VAC', 'HAD_COVID', 'ANXIOUS', 'WORRY',
       'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
       'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF',
       'REC_FREEFOOD', 'OWN_RENT', 'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME',
       'HWEIGHT', 'PWEIGHT', 'SURVEY_START_DATE', 'SURVEY_END_DATE',
       'METRO_AREA', 'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE',
       'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE',
       'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN'],
      dtype='object')

,SCRAM,WEEK,STATE,REGION,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,GENDER_IDENITY,SEXUAL_ORIENTATION,TOTAL_HOUSEHOLD,RECVD_VAC,HAD_COVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,JOBLOSS,EMPLOYED,WORK_SECTOR,EXPNS_DIF,CURFOODSUF,REC_FREEFOOD,OWN_RENT,PRIVHLTH_INS,PUBHLTH_INS,INCOME,HWEIGHT,PWEIGHT,SURVEY_START_DATE,SURVEY_END_DATE,METRO_AREA,LONG_COVID,LONG_COVID_IMPACT,SELFCARE,UNDERSTAND,PRICECHNG,PRICESTRESS,PRICECONCRN,WORK_REMOTE,TSPNDFOOD,TSPNDPRPD,ND_DISPLACE,MEDICAID,HAD_COVID_WHEN
0,V380000001,38,28,2,1965,1,1,6,5,1,2,1,1,2,2,1,2,2,2,1,1,2,2,1,2,1,1,2,2,1,2,6,662.915385,636.350100,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V380000002,38,35,4,1952,1,1,4,1,2,2,2,1,2,1,1,1,1,2,1,1,1,2,1,4,1,1,2,1,1,1,5,536.164089,1046.123591,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V380000003,38,2,4,1954,1,1,3,2,2,2,1,1,2,1,1,1,1,1,1,1,2,2,2,99,1,1,2,1,1,1,4,399.481562,385.689765,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V380000004,38,55,3,1945,1,1,3,1,2,2,2,1,2,1,1,1,1,1,1,1,1,2,2,99,1,1,2,1,1,1,99,6385.449077,11877.653310,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V380000005,38,42,1,1961,1,1,3,1,1,5,4,2,2,1,1,1,1,4,4,4,4,2,2,99,3,1,2,99,1,2,99,21493.336617,59467.996796,2021-09-15,2021-09-27,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99

(59833, 50)

In [47]:
# Display 4q dataframe columns to determine which columns to rename
display("pulse2021_4q_analysis_clean_df columns before rename")
display(pulse2021_4q_analysis_clean_df.columns)

'pulse2021_4q_analysis_clean_df columns before rename'

Index(['SCRAM', 'WEEK', 'EST_ST', 'REGION', 'TBIRTH_YEAR', 'RHISPANIC',
       'RRACE', 'EEDUC', 'MS', 'GENID_DESCRIBE', 'SEXUAL_ORIENTATION',
       'THHLD_NUMPER', 'RECVDVACC', 'HADCOVID', 'ANXIOUS', 'WORRY', 'INTEREST',
       'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'WRKLOSSRV',
       'ANYWORK', 'KINDWORK', 'EXPNS_DIF', 'CURFOODSUF', 'FREEFOOD', 'TENURE',
       'PRIVHLTH', 'PUBHLTH', 'INCOME', 'HWEIGHT', 'PWEIGHT', 'ACTIVITY2',
       'SURVEY_START_DATE', 'SURVEY_END_DATE', 'EST_MSA_CLEAN',
       'LONGCOVID_PLUG', 'SYMPTMIMPCT_PLUG', 'SELFCARE_PLUG',
       'UNDERSTAND_PLUG', 'PRICECHNG_PLUG', 'PRICESTRESS_PLUG',
       'PRICECONCRN_PLUG', 'TWDAYS_PLUG', 'TSPNDFOOD_PLUG', 'TSPNDPRPD_PLUG',
       'ND_DISPLACE_PLUG', 'MEDICAID_PLUG', 'WHENCOVID_PLUG'],
      dtype='object')

In [48]:
# Rename 4q dataframe columns to make them easier to understand and align with other quarter files
pulse2021_4q_analysis_clean_df.columns = ['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC',
                                          'RACE', 'EDUCATION', 'MARITAL_STATUS', 'GENDER_IDENITY', 'SEXUAL_ORIENTATION',
                                          'TOTAL_HOUSEHOLD', 'RECVD_VAC', 'HAD_COVID', 'ANXIOUS', 'WORRY', 'INTEREST',
                                          'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
                                          'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD',
                                          'OWN_RENT', 'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME', 'HWEIGHT', 'PWEIGHT',
                                          'ACTIVITY2', 'SURVEY_START_DATE', 'SURVEY_END_DATE',
                                          'METRO_AREA', 'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE', 'UNDERSTAND',
                                          'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE', 'TSPNDFOOD',
                                          'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN'] 
                  
#Drop 'ACTIVITY2' columns until we decide if needed for our analysis
pulse2021_4q_analysis_clean_df = pulse2021_4q_analysis_clean_df.drop(['ACTIVITY2'], axis=1)

display("pulse2021_4q_analysis_clean_df columns after rename and drop of ACTIVITY2 column")
display(pulse2021_4q_analysis_clean_df.columns)
display(pulse2021_4q_analysis_clean_df.head())
display(pulse2021_4q_analysis_clean_df.shape)

'pulse2021_4q_analysis_clean_df columns after rename and drop of ACTIVITY2 column'

Index(['SCRAM', 'WEEK', 'STATE', 'REGION', 'BIRTH_YEAR', 'HISPANIC', 'RACE',
       'EDUCATION', 'MARITAL_STATUS', 'GENDER_IDENITY', 'SEXUAL_ORIENTATION',
       'TOTAL_HOUSEHOLD', 'RECVD_VAC', 'HAD_COVID', 'ANXIOUS', 'WORRY',
       'INTEREST', 'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING',
       'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'EXPNS_DIF', 'CURFOODSUF',
       'REC_FREEFOOD', 'OWN_RENT', 'PRIVHLTH_INS', 'PUBHLTH_INS', 'INCOME',
       'HWEIGHT', 'PWEIGHT', 'SURVEY_START_DATE', 'SURVEY_END_DATE',
       'METRO_AREA', 'LONG_COVID', 'LONG_COVID_IMPACT', 'SELFCARE',
       'UNDERSTAND', 'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'WORK_REMOTE',
       'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'MEDICAID', 'HAD_COVID_WHEN'],
      dtype='object')

,SCRAM,WEEK,STATE,REGION,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,GENDER_IDENITY,SEXUAL_ORIENTATION,TOTAL_HOUSEHOLD,RECVD_VAC,HAD_COVID,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,JOBLOSS,EMPLOYED,WORK_SECTOR,EXPNS_DIF,CURFOODSUF,REC_FREEFOOD,OWN_RENT,PRIVHLTH_INS,PUBHLTH_INS,INCOME,HWEIGHT,PWEIGHT,SURVEY_START_DATE,SURVEY_END_DATE,METRO_AREA,LONG_COVID,LONG_COVID_IMPACT,SELFCARE,UNDERSTAND,PRICECHNG,PRICESTRESS,PRICECONCRN,WORK_REMOTE,TSPNDFOOD,TSPNDPRPD,ND_DISPLACE,MEDICAID,HAD_COVID_WHEN
0,V390000001S30010132000112,39,1,2,1955,1,1,4,1,1,2,2,1,2,1,1,2,99,2,2,2,2,2,2,99,1,1,2,2,1,1,5,1560.107273,2950.831036,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
1,V390000001S30010930100112,39,1,2,1955,1,1,4,1,2,99,4,1,2,99,99,99,99,99,99,99,99,2,1,99,99,99,99,99,3,3,99,2015.111681,1905.719622,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
2,V390000001S96010845500122,39,1,2,1999,1,4,4,5,2,3,3,1,2,2,2,3,2,1,1,1,2,2,2,99,1,1,2,2,1,2,3,2916.377523,8274.178438,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
3,V390000001S98010895010122,39,1,2,1935,1,1,7,1,1,2,3,1,2,1,1,1,1,1,1,2,1,2,2,99,1,1,2,1,3,1,7,989.102446,2806.224527,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99
4,V390000001S98010931110112,39,1,2,1969,1,2,4,3,2,2,2,1,2,3,3,1,1,2,1,1,2,2,1,2,3,1,2,3,1,2,4,786.707174,1488.000207,2021-09-29,2021-10-11,99999.9,99,99,99,99,99,99,99,99,99,99,99,99,99

(57064, 50)

In [49]:
# Reorder survey columns that will be used for analysis
all_analysis_cols = ['SURVEY_START_DATE', 'SURVEY_END_DATE', 'REGION', 'STATE', 'METRO_AREA','BIRTH_YEAR', 'HISPANIC',
                     'RACE', 'EDUCATION', 'MARITAL_STATUS', 'GENDER_IDENITY', 'SEXUAL_ORIENTATION', 'HAD_COVID',
                     'HAD_COVID_WHEN', 'LONG_COVID', 'LONG_COVID_IMPACT','ANXIOUS', 'WORRY', 'INTEREST', 'DOWN',
                     'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'SELFCARE', 'UNDERSTAND', 'JOBLOSS', 'EMPLOYED',
                     'WORK_SECTOR', 'WORK_REMOTE', 'PRIVHLTH_INS', 'PUBHLTH_INS','MEDICAID', 'INCOME',                   
                     'TOTAL_HOUSEHOLD', 'RECVD_VAC', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD', 'OWN_RENT', 'PRICECHNG',
                     'PRICESTRESS', 'PRICECONCRN', 'TSPNDFOOD', 'TSPNDPRPD', 'ND_DISPLACE', 'SCRAM', 'WEEK', 'HWEIGHT',
                     'PWEIGHT']
                    
# Create new dataframe for analysis
pulse2021_1q_analysis_focused_all_cols_df = pulse2021_1q_analysis_clean_df[all_analysis_cols]
pulse2021_2q_analysis_focused_all_cols_df = pulse2021_2q_analysis_clean_df[all_analysis_cols]
pulse2021_3q_analysis_focused_all_cols_df = pulse2021_3q_analysis_clean_df[all_analysis_cols]
pulse2021_4q_analysis_focused_all_cols_df = pulse2021_4q_analysis_clean_df[all_analysis_cols]
print("pulse2021 1q_4q analysis_focused_all_cols_df dataframes created")

pulse2021 1q_4q analysis_focused_all_cols_df dataframes created

In [50]:
# Concatenate 4 quarters of survey data to create 2021 all columns file
pulse2021_survey_data_all_cols_df = pd.concat([pulse2021_1q_analysis_focused_all_cols_df,
                                               pulse2021_2q_analysis_focused_all_cols_df,
                                               pulse2021_3q_analysis_focused_all_cols_df,
                                               pulse2021_4q_analysis_focused_all_cols_df],
                                               ignore_index=True)

In [51]:
# Save 2021 all columns survey file for analysis
pulse2021_survey_data_all_cols_df.to_csv('Resources/pulse2021_survey_data_all_cols.csv', index=False)
print("pulse2021_survey_data_all_cols.csv file saved")

pulse2021_survey_data_all_cols.csv file saved

In [52]:
# Display 2021 survey all columns file columns
display(pulse2021_survey_data_all_cols_df.columns)

Index(['SURVEY_START_DATE', 'SURVEY_END_DATE', 'REGION', 'STATE', 'METRO_AREA',
       'BIRTH_YEAR', 'HISPANIC', 'RACE', 'EDUCATION', 'MARITAL_STATUS',
       'GENDER_IDENITY', 'SEXUAL_ORIENTATION', 'HAD_COVID', 'HAD_COVID_WHEN',
       'LONG_COVID', 'LONG_COVID_IMPACT', 'ANXIOUS', 'WORRY', 'INTEREST',
       'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'SELFCARE',
       'UNDERSTAND', 'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'WORK_REMOTE',
       'PRIVHLTH_INS', 'PUBHLTH_INS', 'MEDICAID', 'INCOME', 'TOTAL_HOUSEHOLD',
       'RECVD_VAC', 'EXPNS_DIF', 'CURFOODSUF', 'REC_FREEFOOD', 'OWN_RENT',
       'PRICECHNG', 'PRICESTRESS', 'PRICECONCRN', 'TSPNDFOOD', 'TSPNDPRPD',
       'ND_DISPLACE', 'SCRAM', 'WEEK', 'HWEIGHT', 'PWEIGHT'],
      dtype='object')

In [53]:
# Display 2021 survey all columns file shape
display(pulse2021_survey_data_all_cols_df.shape)

(272486, 50)

In [54]:
print("pulse2021_survey_data_all_cols is ready for analysis")

pulse2021_survey_data_all_cols is ready for analysis

In [55]:
# Reduce and reorder survey columns that will be used for analysis
analysis_cols = ['SURVEY_START_DATE', 'SURVEY_END_DATE', 'REGION', 'STATE', 'METRO_AREA','BIRTH_YEAR', 'HISPANIC',
                 'RACE', 'EDUCATION', 'MARITAL_STATUS', 'GENDER_IDENITY', 'SEXUAL_ORIENTATION', 'HAD_COVID',
                 'HAD_COVID_WHEN', 'LONG_COVID', 'LONG_COVID_IMPACT','ANXIOUS', 'WORRY', 'INTEREST', 'DOWN',
                 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'SELFCARE', 'UNDERSTAND', 'JOBLOSS', 'EMPLOYED',
                 'WORK_SECTOR', 'WORK_REMOTE', 'PRIVHLTH_INS', 'PUBHLTH_INS','MEDICAID', 'INCOME']

# Create new dataframe for analysis
pulse2021_1q_analysis_focused_df = pulse2021_1q_analysis_clean_df[analysis_cols]
pulse2021_2q_analysis_focused_df = pulse2021_2q_analysis_clean_df[analysis_cols]
pulse2021_3q_analysis_focused_df = pulse2021_3q_analysis_clean_df[analysis_cols]
pulse2021_4q_analysis_focused_df = pulse2021_4q_analysis_clean_df[analysis_cols]
print("pulse2021 1q_4q analysis_focused_df dataframes created")

pulse2021 1q_4q analysis_focused_df dataframes created

In [56]:
# Display first 5 rows of analysis dataframes
display(pulse2021_1q_analysis_focused_df.head())
display(pulse2021_2q_analysis_focused_df.head())
display(pulse2021_3q_analysis_focused_df.head())
display(pulse2021_4q_analysis_focused_df.head())

,SURVEY_START_DATE,SURVEY_END_DATE,REGION,STATE,METRO_AREA,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,GENDER_IDENITY,SEXUAL_ORIENTATION,HAD_COVID,HAD_COVID_WHEN,LONG_COVID,LONG_COVID_IMPACT,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,SELFCARE,UNDERSTAND,JOBLOSS,EMPLOYED,WORK_SECTOR,WORK_REMOTE,PRIVHLTH_INS,PUBHLTH_INS,MEDICAID,INCOME
0,2021-02-03,2021-02-15,2,1,99999.9,1957,1,1,3,1,2,99,2,99,99,99,2,1,1,2,99,99,99,99,99,99,99,2,99,99,1,1,99,3
1,2021-02-03,2021-02-15,2,1,99999.9,1977,1,1,6,3,1,99,2,99,99,99,1,1,1,1,99,99,99,99,99,99,99,1,2,99,1,2,99,4
2,2021-02-03,2021-02-15,2,1,99999.9,1944,1,1,4,1,2,99,2,99,99,99,1,1,1,1,99,99,99,99,99,99,99,2,99,99,3,1,99,2
3,2021-02-03,2021-02-15,2,1,99999.9,1947,1,1,6,2,2,99,2,99,99,99,99,99,99,99,99,99,99,99,99,99,99,2,99,99,3,3,99,99
4,2021-02-03,2021-02-15,2,1,99999.9,1978,1,4,4,1,1,99,2,99,99,99,99,99,99,99,99,99,99,99,99,99,99,1,2,99,3,3,99,99

,SURVEY_START_DATE,SURVEY_END_DATE,REGION,STATE,METRO_AREA,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,GENDER_IDENITY,SEXUAL_ORIENTATION,HAD_COVID,HAD_COVID_WHEN,LONG_COVID,LONG_COVID_IMPACT,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,SELFCARE,UNDERSTAND,JOBLOSS,EMPLOYED,WORK_SECTOR,WORK_REMOTE,PRIVHLTH_INS,PUBHLTH_INS,MEDICAID,INCOME
0,2021-04-28,2021-05-10,2,1,99999.9,1977,1,1,7,1,2,99,2,99,99,99,99,99,99,99,99,99,99,99,99,99,2,1,2,99,3,3,99,99
1,2021-04-28,2021-05-10,2,1,99999.9,1952,1,1,7,1,1,99,2,99,99,99,1,1,1,1,1,1,1,1,99,99,2,2,99,99,1,1,99,7
2,2021-04-28,2021-05-10,2,1,99999.9,2000,1,1,4,5,2,99,1,99,99,99,1,1,1,1,99,99,99,99,99,99,2,1,3,99,3,3,99,99
3,2021-04-28,2021-05-10,2,1,99999.9,1965,1,1,4,4,2,99,2,99,99,99,99,99,99,99,99,99,99,99,99,99,2,2,99,99,3,3,99,99
4,2021-04-28,2021-05-10,2,1,99999.9,1948,1,1,3,2,1,99,2,99,99,99,1,1,1,1,2,1,2,1,99,99,2,2,99,99,3,1,99,3

,SURVEY_START_DATE,SURVEY_END_DATE,REGION,STATE,METRO_AREA,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,GENDER_IDENITY,SEXUAL_ORIENTATION,HAD_COVID,HAD_COVID_WHEN,LONG_COVID,LONG_COVID_IMPACT,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,SELFCARE,UNDERSTAND,JOBLOSS,EMPLOYED,WORK_SECTOR,WORK_REMOTE,PRIVHLTH_INS,PUBHLTH_INS,MEDICAID,INCOME
0,2021-09-15,2021-09-27,2,28,99999.9,1965,1,1,6,5,1,2,2,99,99,99,2,1,2,2,2,1,1,2,99,99,2,1,2,99,1,2,99,6
1,2021-09-15,2021-09-27,4,35,99999.9,1952,1,1,4,1,2,2,2,99,99,99,1,1,1,1,2,1,1,1,99,99,2,1,4,99,1,1,99,5
2,2021-09-15,2021-09-27,4,2,99999.9,1954,1,1,3,2,2,2,2,99,99,99,1,1,1,1,1,1,1,2,99,99,2,2,99,99,1,1,99,4
3,2021-09-15,2021-09-27,3,55,99999.9,1945,1,1,3,1,2,2,2,99,99,99,1,1,1,1,1,1,1,1,99,99,2,2,99,99,1,1,99,99
4,2021-09-15,2021-09-27,1,42,99999.9,1961,1,1,3,1,1,5,2,99,99,99,1,1,1,1,4,4,4,4,99,99,2,2,99,99,1,2,99,99

,SURVEY_START_DATE,SURVEY_END_DATE,REGION,STATE,METRO_AREA,BIRTH_YEAR,HISPANIC,RACE,EDUCATION,MARITAL_STATUS,GENDER_IDENITY,SEXUAL_ORIENTATION,HAD_COVID,HAD_COVID_WHEN,LONG_COVID,LONG_COVID_IMPACT,ANXIOUS,WORRY,INTEREST,DOWN,SEEING,HEARING,MOBILITY,REMEMBERING,SELFCARE,UNDERSTAND,JOBLOSS,EMPLOYED,WORK_SECTOR,WORK_REMOTE,PRIVHLTH_INS,PUBHLTH_INS,MEDICAID,INCOME
0,2021-09-29,2021-10-11,2,1,99999.9,1955,1,1,4,1,1,2,2,99,99,99,1,1,2,99,2,2,2,2,99,99,2,2,99,99,1,1,99,5
1,2021-09-29,2021-10-11,2,1,99999.9,1955,1,1,4,1,2,99,2,99,99,99,99,99,99,99,99,99,99,99,99,99,2,1,99,99,3,3,99,99
2,2021-09-29,2021-10-11,2,1,99999.9,1999,1,4,4,5,2,3,2,99,99,99,2,2,3,2,1,1,1,2,99,99,2,2,99,99,1,2,99,3
3,2021-09-29,2021-10-11,2,1,99999.9,1935,1,1,7,1,1,2,2,99,99,99,1,1,1,1,1,1,2,1,99,99,2,2,99,99,3,1,99,7
4,2021-09-29,2021-10-11,2,1,99999.9,1969,1,2,4,3,2,2,2,99,99,99,3,3,1,1,2,1,1,2,99,99,2,1,2,99,1,2,99,4

In [57]:
# Display shape of analysis dataframes
display(pulse2021_1q_analysis_focused_df.shape)
display(pulse2021_2q_analysis_focused_df.shape)
display(pulse2021_3q_analysis_focused_df.shape)
display(pulse2021_4q_analysis_focused_df.shape)

(77122, 34)

(78467, 34)

(59833, 34)

(57064, 34)

In [58]:
# Concatenate 4 quarters of survey data to create 2021 file
pulse2021_survey_data_df = pd.concat([pulse2021_1q_analysis_focused_df, pulse2021_2q_analysis_focused_df,
                                  pulse2021_3q_analysis_focused_df, pulse2021_4q_analysis_focused_df],
                                  ignore_index=True)

In [59]:
# Save 2021 survey file for analysis
pulse2021_survey_data_df.to_csv('Resources/pulse2021_survey_data.csv', index=False)
print("pulse2021_survey_data.csv file saved")

pulse2021_survey_data.csv file saved

In [60]:
# Display 2021 survey file columns
display(pulse2021_survey_data_df.columns)

Index(['SURVEY_START_DATE', 'SURVEY_END_DATE', 'REGION', 'STATE', 'METRO_AREA',
       'BIRTH_YEAR', 'HISPANIC', 'RACE', 'EDUCATION', 'MARITAL_STATUS',
       'GENDER_IDENITY', 'SEXUAL_ORIENTATION', 'HAD_COVID', 'HAD_COVID_WHEN',
       'LONG_COVID', 'LONG_COVID_IMPACT', 'ANXIOUS', 'WORRY', 'INTEREST',
       'DOWN', 'SEEING', 'HEARING', 'MOBILITY', 'REMEMBERING', 'SELFCARE',
       'UNDERSTAND', 'JOBLOSS', 'EMPLOYED', 'WORK_SECTOR', 'WORK_REMOTE',
       'PRIVHLTH_INS', 'PUBHLTH_INS', 'MEDICAID', 'INCOME'],
      dtype='object')

In [61]:
# Display 2021 survey file shape
display(pulse2021_survey_data_df.shape)

(272486, 34)

In [62]:
print("pulse2021_survey_data is ready for analysis")

pulse2021_survey_data is ready for analysis